### ISSUE TITLE
Seeing ten second p99 pulsar_client_consumer_processing_time_seconds_bucket values

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar-client-go#1010]
#### Expected behavior
We have a multi-threaded golang app streaming data from Pulsar, doing CPU intensive analysis and streaming data back to Pulsar. 
We started monitoring the new Pulsar Go client metrics (which are great BTW!) and noticed something odd.

Query we are running is 
```
histogram_quantile(0.99, sum(rate(pulsar_client_consumer_processing_time_seconds_bucket{xxxxx,pulsar_namespace=~'yyyyyy', pod=~'zzzzzz'}[2m])) by (le, pulsar_tenant, pulsar_namespace))
```

#### Actual behavior

See 
![image](https://user-images.githubusercontent.com/62910985/232056862-c660b878-369f-4eeb-b893-1f22daaaa360.png)

So far all our inspections suggest there are no delays but looking for assistance in ways to confirm that.

In other environments we do not see that 
![image](https://user-images.githubusercontent.com/62910985/232057996-4e4cbd2c-4e47-4603-9215-b080ea207bac.png)

Pod CPU usage is below requests CPU (and pod CPU limits are > requests)

#### Steps to reproduce

Sorry have no repro steps - just looking for ideas / help or at least confirmation that the metric is working appropriately or that we are graphing and interpreting it appropriately.

#### System configuration
**Pulsar version**: 2.10.3
Client Version - `0.10.0`

UPDATE: FYI we are using the Reader Interface to read this data stream and using the default `ReceiverQueueSize` of 1,000 
No idea if that makes any difference
https://github.com/apache/pulsar-client-go/blob/55f0c7cfda647b5ed0c19882790e92418b8bd651/pulsar/reader.go#L63-L68

**Comment by BewareMyPower** [comment]
The processing time actually records the time that a message id is processed. By default, the batch index ACK is  disabled, so
1. If the message is not batched, the processing time is nearly 0.
2. Otherwise, given the batch size `N`, the processing time is the interval that started when the 1st message in the batch was received and finished when all `N` messages were acknowledged.

I think this metric name is somehow not accurate and confusing.

BTW, I found when batch index ACK is enabled, this metric won't be updated. And currently the `Reader` interface does not support the batch index ACK yet.

**Comment by frankjkelly** [comment]
> I think this metric name is somehow not accurate and confusing.
Thanks @BewareMyPower can you add some more details?

**Comment by BewareMyPower** [comment]
> * If the message is not batched, the processing time is nearly 0.
> * Otherwise, given the batch size `N`, the processing time is the interval that started when the 1st message in the batch was received and finished when all `N` messages were acknowledged.

I think the explanations above are already detailed. This metric actually represents the time of preprocessing a message ID. For a non-batch message, its message ID does not need to be preprocessed so the time is nearly 0. For a batched message, I think the most time is to wait all messages in the same batch are received.

**Comment by frankjkelly** [comment]
Ah ok - thanks @BewareMyPower 
From our side we've identified a cause of our high consumer processing time (somehow related to the choice of EC2 node in our EKS cluster strangely).
Do you think we should repurpose this issue to improve the documentation of the metric or should we close this and create a new issue?

Thanks!

**Comment by BewareMyPower** [comment]
It seems that we don't have any document for these prometheus metrics yet. It would be good to add some docs.

And since you already found the reason of the high processing time, I think we can close this issue for now.
