### ISSUE TITLE
Schema.hash is ressource intensive

### ISSUE THREAD

**Issue by bpereto** [apache/pulsar-client-go#1021]
#### Expected behavior

Usage of pulsar producer with Schema performs well or similar when producing without Schema.

#### Actual behavior
When a schema is enabled in the producer, the produce throughput is degraded.

I profiled the application and the result indicates that `Schema.hash` is using 30% CPU time.

https://github.com/apache/pulsar-client-go/commit/ea6eccf7ddad548a1ad977a0b72a61b894e6d248 introduced a function `Schema.hash` with `sha256`.
This might be not noticeable on low event throughput, but indicates a problem with high volume.
Producing 300k events/s is not a problem at all when no schema is used.

![profile002](https://github.com/apache/pulsar-client-go/assets/1131885/68e3e960-4e6e-44a9-86d0-aea87ec7fe38)

I can see at https://github.com/apache/pulsar-client-go/blob/27e36250f35094b203483c946bc4406c6119ce62/pulsar/producer_partition.go#L537 that there is some caching logic for schema, and `Schema.Get` uses the hash of the Schema for cache lookup.

May I suggest to use a more performant hash algorithm than sha256? Maybe there is also another possibility to achive the goal of looking up the schema cache in a more performant way.

I'm open to contribute and test different approaches.

#### Steps to reproduce

- Pulsar Producer with Schema
- Enable Profiling
- Produce 200k events/s

#### System configuration
**Pulsar version**: 2.11.1

**Comment by tisonkun** [comment]
@bpereto Please fill in more details about what you're doing, how you measure the performance, and how it performs "bad".

Otherwise, we can do nothing for a statement.

**Comment by bpereto** [comment]
Sorry, It created the issue before I could fill it out completely.

**Comment by bpereto** [comment]
Updated it and added profiling information.

**Comment by bpereto** [comment]
I will test a hash function implementation with [golang/hash/maphash](https://pkg.go.dev/hash/maphash) as referenced by the pull request.

**Comment by bpereto** [comment]
Tested it, works as intended for me.
