### ISSUE TITLE
Go-rate license is still present

### ISSUE THREAD

**Issue by artursouza** [apache/pulsar-client-go#1023]
#### Expected behavior

go-rate license is not present under distribution/

#### Actual behavior

PR https://github.com/apache/pulsar-client-go/issues/952 did not remove it

#### Steps to reproduce

Any project with FOSSA scanning that depends on this project will flag it.

**Comment by tisonkun** [comment]
Thanks for reportig this issue. Yes I omitted the related LICENSE file and here is a follow-up https://github.com/apache/pulsar-client-go/pull/1028.

I'll appreciate it if you can spot if there is still some dangling refs.
