### ISSUE TITLE
Producer deadlocks when pulsar downtime

### ISSUE THREAD

**Issue by hailin0** [apache/pulsar-client-go#107]
#### Expected behavior

Producer works normally after pulsar restart

#### Actual behavior

producer#flush deadlock after pulsar restart

#### Steps to reproduce

	for  {
		asyncMsg := pulsar.ProducerMessage{
			Payload: []byte(fmt.Sprintf("async-message")),
		}

		producer.SendAsync(ctx, &asyncMsg, func(mid pulsar.MessageID, msg *pulsar.ProducerMessage, err error) {
			if err != nil { log.Fatal(err) }
		})

		// deadlock
		producer.Flush() 
	}

=======================
Running the above program and restarting pulsar will cause producer#flush deadlock

#### System configuration
**Pulsar version**: latest

**Comment by jiazhai** [comment]
Thanks @reugn for helping on this issue

**Comment by hailin0** [comment]
@reugn 
I tested [pr 108](https://github.com/apache/pulsar-client-go/pull/108) but it didn't recover

**Comment by wolfstudy** [comment]
@reugn Maybe the issue is similar to #124. Can you try it again?
