### ISSUE TITLE
[Improve] Rename `DisableBlockIfQueueFull` to `BlockIfQueueFull` as JAVA client and have the same default value

### ISSUE THREAD

**Issue by gunli** [apache/pulsar-client-go#1088]
#### Expected behavior

1. Rename the config option 'DisableBlockIfQueueFull' to 'BlockIfQueueFull', same as it is in JAVA client; 
2. After renaming, set the default value to `false`, same as it is in JAVA client; 

#### Actual behavior
1. There is a config option to controls whether Send and SendAsync block if producer's message queue is full; 
2. In JAVA client, this config option is called 'blockIfQueueFull', and the default value is `false`, meaning no block if queue is full. https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ProducerConfigurationData.java#L85
3. In Go client, this config option is called `DisableBlockIfQueueFull`, and the default value is `false`, meaing block if queue is full. https://github.com/apache/pulsar-client-go/blob/master/pulsar/producer.go#L102
4. The name `DisableBlockIfQueueFull` and the default value `false` is "double negative", is difficult to understand.

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

**Comment by gunli** [comment]
Hi @RobertIndie @shibd , would you please check if improve issue is acceptable, if it is accepted, I will summit a PR to make it done.

**Comment by shibd** [comment]
This is a break change. I think we need keep it.

BTW: That default value reason can refer to: https://github.com/apache/pulsar-client-go/pull/394#discussion_r527268981

**Comment by RobertIndie** [comment]
It's designed that way on purpose. The default value of bool is false. Therefore we need to use `DisaleBlockIfQueueFull` instead of `BlockIfQueueFull`. Unless we add a new method `NewProducerOptions` to create a producer. But I don't think such a change is necessary. 
This would be a breaking change and we need to keep the old one.
