### ISSUE TITLE
Unable to import pulsar admin Packages in Go

### ISSUE THREAD

**Issue by swarooplendi** [apache/pulsar-client-go#1093]
#### Expected behavior

To pull github.com/apache/pulsar-client-go/pulsaradmin when command go mod tidy run

#### Actual behavior
with go lang version 1.18 to 1.21
needed to import 
import (
	"context"
	"fmt"
	"math/rand"
	"time"

	"github.com/apache/pulsar-client-go/pulsar"
	`"github.com/apache/pulsar-client-go/pulsaradmin"`
)

when imported using command go mod tidy or other imports it throws error

go: gotest imports
	github.com/apache/pulsar-client-go/pulsaradmin: module github.com/apache/pulsar-client-go@latest found (v0.11.0), but does not contain package github.com/apache/pulsar-client-go/pulsaradmin

#### Steps to reproduce
have `"github.com/apache/pulsar-client-go/pulsaradmin"` in import 
with some function of https://github.com/apache/pulsar-client-go/tree/master/pulsaradmin
RUN go mod init <name>
RUN go mod tidy
#### System configuration
**Pulsar version**: x.y

**Comment by jichmi** [comment]
Look like pulsaradmin is not released at v0.11.0
https://github.com/apache/pulsar-client-go/tree/branch-0.11.0

**Comment by kecona** [comment]
You can try the following command:

```
go get github.com/apache/pulsar-client-go
```

**Comment by haxung** [comment]
Write this in `go.mod` . It's helpful for me.

```
require github.com/apache/pulsar-client-go v0.9.1-0.20231101153545-0845e7389aff
```

That `pulsaradmin` doesn't merge to any tags, so cannot import it. However we can use `commit` number, like `0845e73`.

**Comment by swarooplendi** [comment]
> Write this in `go.mod` . It's helpful for me.
> 
> ```
> require github.com/apache/pulsar-client-go v0.9.1-0.20231101153545-0845e7389aff
> ```
> 
> That `pulsaradmin` doesn't merge to any tags, so cannot import it. However we can use `commit` number, like `0845e73`.

It worked thanks for the help
