### ISSUE TITLE
 The pulsar go client missing data when transfer

### ISSUE THREAD

**Issue by sunlc210** [apache/pulsar-client-go#114]
Now I found one problem relate to pulsar go client 

The whole process of mine is   csv file  filebeatpulsar flume hive

At past time I verified the data count ,found that the data by this path missing about 0.46% compare with the path of logstashkafka .

No idea the reason why ,so I tried below steps 

1 Reduce the amount of data from 100% to 50%, excluding data loss caused by too much pressure in the pulsar cluster, the data loss is still 0.46%
2 Reduce the amount of data from 50% to 10%, make the pulsar cluster stress-free, and the data loss is still 0.46%
3 Use bin / pulsar-perf to quantitatively send test test data to the pulsar cluster, which is 100% acceptable, eliminating the problems of the pulsar cluster
4 Quantitatively send test data to the pulsar cluster with filebeat. 99.6% can receive it (send 36077, receive 35091)
 

I put the data file in the attachment. Please take a look at this problem. Now the loss rate is about five thousandths, which is a little too large.

Another thing to say, I use the asynchronous sending of the go client, which has been confirmed with @tuteng

Hopefully your response

**Comment by jiazhai** [comment]
@sunlc210 Thanks for reporting this issue. 
Is it reproduce-able to simulate the filebeat behavior by purely pulsar go client, This is very helpful to the fix.

**Comment by sunlc210** [comment]
I'm sorry, I can't use goclient, but I sent the data file to @xiaolong and @tuteng
