### ISSUE TITLE
dependency dvsekhvalnov/jose2go v1.5.0 is vulnerable

### ISSUE THREAD

**Issue by richelieu-yang** [apache/pulsar-client-go#1149]
#### Actual behavior

![Uploading 20231226144510.jpg…]()

**Comment by richelieu-yang** [comment]
![20231226144510](https://github.com/apache/pulsar-client-go/assets/51251717/9b841826-d785-467f-a25d-9d6ce19c5a28)

**Comment by RobertIndie** [comment]
This has been fixed by https://github.com/apache/pulsar-client-go/pull/1150
