### ISSUE TITLE
Data race: type client.handers map is not concurrent safe

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [apache/pulsar-client-go#118]
#### Expected behavior

Client should be concurrent safe.  Writes to client.handlers marking them closable should never cause a panic. 

#### Actual behavior

Current implementation allows a race condition since there is no sync.Mutex or something similar protect concurrent writes to the map index.  Examples:

- https://github.com/apache/pulsar-client-go/blob/e65b4795a5928d7989c3089dca5e5243439160dd/pulsar/client_impl.go#L96
- https://github.com/apache/pulsar-client-go/blob/e65b4795a5928d7989c3089dca5e5243439160dd/pulsar/client_impl.go#L106

#### Steps to reproduce

Run two goroutines creating subscribers or producers... or just run some tests using the race detector.

I'll submit a PR for this in a few minutes.

**Comment by Jim-Lambert-Bose** [comment]
https://github.com/apache/pulsar-client-go/pull/119/files

**Comment by wolfstudy** [comment]
The issue has been fixed, will close it.
