### ISSUE TITLE
Pulsar Producer send Avro message schema

### ISSUE THREAD

**Issue by ThinhLe30** [apache/pulsar-client-go#1183]
Hi. I'm here to ask is there any example of Pulsar Producer send Avro message schema. Thanks a lot.

**Comment by RobertIndie** [comment]
Can this example help you? https://github.com/apache/pulsar-client-go/blob/c2ca7e81f0c609cd8fb7b13695664519e63e4501/pulsar/schema_test.go#L277-L319

**Comment by ThinhLe30** [comment]
@RobertIndie thanks a lot
