### ISSUE TITLE
[BUG] The process will block if close client or producer when pulsar server is down.

### ISSUE THREAD

**Issue by asddongmen** [apache/pulsar-client-go#1190]
#### Expected behavior

Tell us what should happen

When calling the client or producer close method, it should fail and return.

#### Actual behavior

Tell us what happens instead

Instead of failing and returning, the close method keeps blocking if the pulsar cluster is down.

#### Steps to reproduce

How can we reproduce the issue

1. Deploy a standalone pulsar server.
2. Connect a go client to the server.
3. Shut down the server.
4. Close the client.
5. Observe that the process blocks.

#### System configuration
**Pulsar version**: pulsar-client-go v0.11.0

**Comment by crossoverJie** [comment]
Could you provide your test case? I can't reproduce.

```go
func TestCloseBroker(t *testing.T)  {
	client, err := NewClient(ClientOptions{
		URL: lookupURL,
	})
	assert.Nil(t, err)

	t.Logf("connect success\n")
	time.Sleep(time.Second * 30)
    
	// shutdown broker
	client.Close()
	t.Logf("client close sucess")

}
```

Buf if you create producer/consumer, the client will try to reconnect, maybe the process is blocked as you described.
