### ISSUE TITLE
Closed reader does not return in Next

### ISSUE THREAD

**Issue by Gilthoniel** [apache/pulsar-client-go#1218]
#### Expected behavior

After closing a reader, I would expect the `Next` function to return an error that the reader is closed.

#### Actual behavior

It blocks forever.

#### Steps to reproduce

Close the reader then call the `Next`, it will not return:

```Go
client, err := pulsar.NewClient(pulsar.ClientOptions{URL: "pulsar://localhost:6650"})
if err != nil { ... }

defer client.Close()

reader, err := client.CreateReader(pulsar.ReaderOptions{ ... })
if err != nil { ... }

reader.Close()

// Here I would expect to directly return an error but it blocks forever.
reader.Next(context.Background())
```

#### System configuration
**Pulsar version**: v3.0
**Pulsar client**: v12.1

**Comment by Gilthoniel** [comment]
An simple fix would be to add a case to the select to return when the consumer `closed` channel is closed but I don't know if that behavior is on purpose at the first place.

**Comment by RobertIndie** [comment]
Thanks for reporting this.

> An simple fix would be to add a case to the select to return when the consumer `closed` channel is closed

Yes. I think this should be correct behavior.

**Comment by Gilthoniel** [comment]
Thanks @RobertIndie , I've opened #1219 for a potential fix.
