### ISSUE TITLE
[doc] Please provide an example of enabling transaction consumption at the production environment level

### ISSUE THREAD

**Issue by zcola** [apache/pulsar-client-go#1222]
Please provide an example of enabling transaction consumption at the production environment level

**Comment by geniusjoe** [comment]
Maybe You can refer to the txn [Get Start](https://pulsar.apache.org/docs/next/txn-use/) Go doc.

**Comment by RobertIndie** [comment]
Added at https://github.com/apache/pulsar-site/pull/948
