### ISSUE TITLE
[Question]Zero value of ReceiverQueueSize

### ISSUE THREAD

**Issue by g41797** [apache/pulsar-client-go#1223]
For php client was discussed [#26](https://github.com/ikilobyte/pulsar-client-php/issues/26)

According to implementation
```go
if options.ReceiverQueueSize <= 0 {
	options.ReceiverQueueSize = 1000
}
```
According to [recommendations](https://pulsar.apache.org/docs/next/cookbooks-message-queue/#client-configuration-changes):
"...set the consumers' receiver queue size very low (potentially even to **_0_** if necessary)..."

So according to docs, I need set this value to 0, but go client sets it to 1000.

Please clarify

**Comment by crossoverJie** [comment]
https://github.com/apache/pulsar/blob/0219921b5b7cd157092ac8f2d86ab7e60787d36c/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java#L316-L318

https://github.com/apache/pulsar/blob/bb83502ebe9a7b50070b988735925b247cfa8fef/pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ZeroQueueSizeTest.java#L103-L137


@RobertIndie I think we should be consistent with the Java client.

**Comment by g41797** [comment]
[I tested it and set it to 0, the consumer will not receive the message](https://github.com/ikilobyte/pulsar-client-php/issues/26#issuecomment-2133087791)

The main question - **_is recommendation to set receiveQueueSize to 0 is right_**.

consistent code - OK
but what is the behavior of pulsar for this case?

**Comment by crossoverJie** [comment]
Because of `client-go` missing a [ZeroQueueConsumerImpl](https://github.com/apache/pulsar/blob/8c50a6c2e91c81dbf187ce5e66cb39e2758a741e/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ZeroQueueConsumerImpl.java#L42), I'll fix this issue later.

**Comment by g41797** [comment]
Does it mean that it's client side flow and server does not care?
