### ISSUE TITLE
How is pulsaradmin initialized with username and password

### ISSUE THREAD

**Issue by li-zeyuan** [apache/pulsar-client-go#1224]

**Comment by crossoverJie** [comment]
You can refer to here to configure admin token:

https://github.com/apache/pulsar-client-go/blob/2d51323103a65ba522dc73f56f052cc81d663245/pulsaradmin/pkg/admin/brokers_test.go#L32-L35

**Comment by RobertIndie** [comment]
Yes. And you can configure the authentication using these two parameters if you want to use other Auth methods:
https://github.com/apache/pulsar-client-go/blob/2d51323103a65ba522dc73f56f052cc81d663245/pulsaradmin/pkg/admin/config/config.go#L33-L35

But Pulsar doesn't support using the username/pasword for the authentication. For the supported Auth methods, you can check here: https://pulsar.apache.org/docs/next/security-overview/

**Comment by li-zeyuan** [comment]
Thank you very much.

**Comment by crossoverJie** [comment]
Closed as answered.
