### ISSUE TITLE
ackReq Variable Assignment in Code

### ISSUE THREAD

**Issue by zhangweiii** [apache/pulsar-client-go#1233]
https://github.com/apache/pulsar-client-go/blob/827d68273830d1038983aeb2750189a408d49cd5/pulsar/consumer_partition.go#L731-L748

Hi, I noticed an issue in the code at line 733 where ackReq is assigned using :=, which creates a new variable. This results in ackReq always being nil, and consequently, the code at line 748 never gets executed. Shouldn't the check for ackReq.Err be placed after line 743 instead? OR use `=` instead `:=`

**Comment by crossoverJie** [comment]
@zhangweiii Thank you for the feedback on this issue.
