### ISSUE TITLE
Readers leak timers when closed

### ISSUE THREAD

**Issue by MishimaPorte** [apache/pulsar-client-go#1262]
#### Expected behavior

Readers should call `ticker.Stop()` on `timedAckGroupingTracker` when they are closed (e.g. when a reader is closed).

#### Actual behavior

The `ticker.Stop` method is never called on the `timedAckGroupingTracker` member ticker, and so it is leaked.

#### Steps to reproduce

Create and close a substantial amount of Reader instances (using client.CreateReader()). After a substantial amount of Tickers is leaked, you will notice massive performance penalties due to go runtime's handling of all the leaked tickers and increasing amounts of Ticker objects allocated (the picture is from the standard go pprof tool, showing 90Mb of Ticker objects allocated).

![the_bad](https://github.com/user-attachments/assets/436928dd-7393-4d45-9c53-71c680077ec8)

#### System configuration
**Pulsar version**: 2.10

**Comment by geniusjoe** [comment]
Do you mean we need some code snippet like below?
```
func (t *timedAckGroupingTracker) close() {
	t.flushAndClean()
	if t.exitCh != nil {
		close(t.exitCh)
	}
	if t.ticker != nil {
		t.ticker.Stop()
	}
}
```
