### ISSUE TITLE
consumer is closed, but consumer.Recieve() is blocked instead of throwing an exception

### ISSUE THREAD

**Issue by dsmlily** [apache/pulsar-client-go#140]
client, err := pulsar.NewClient(pulsar.ClientOptions{URL: "pulsar://localhost:6650"})
	if err != nil {
		log.Fatal(err)
	}

	defer client.Close()

	consumer, err := client.Subscribe(pulsar.ConsumerOptions{
		Topic:            "topic1",
		SubscriptionName: "my-sub",
		Type:             pulsar.Shared,
	})
	if err != nil {
		log.Fatal(err)
	}

	if err := consumer.Unsubscribe(); err != nil {
		log.Fatal(err)
	} 
	consumer.Close()

	for  {
		fmt.Printf("receive msg ...")
		msg, err := consumer.Receive(context.Background())
		if err != nil {
			log.Fatal(err)
		}

		fmt.Printf("Received message msgId: %#v -- content: '%s'\n",
			msg.ID(), string(msg.Payload()))

		consumer.Ack(msg)
	}

**Comment by wolfstudy** [comment]
@dsmlily The issue has been fixed, will close it.
