### ISSUE TITLE
[Consumer && Message Impl] Thinking about some code design

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar-client-go#15]
hello @merlimat I am implementing the implementation of consumer and message related, there are several code design issues I want to communicate with you.

First: Is `Message` defined as struct more reasonable or as interface is more reasonable?

Second: Whether the `ConsumerMessage` struct can be replaced with a Message struct.

These two questions are related. For this, my idea is that we can define a Message as a struct that contains the fields that make up a message, for example:

```
type Message struct {
	ID          MessageID
	Topic       string
	Properties  map[string]string
	Payload     []byte
	PublishTime time.Time
	EventTime   time.Time
	Key         string
}
```

**Comment by wolfstudy** [comment]
```
type ConsumerMessage struct {
	Consumer
	Message
}
```

In fact, all we need is `Message`, so here we can use Message struct to handle the related logic.

**Comment by jiazhai** [comment]
@wolfstudy Is this issue still need?

**Comment by wolfstudy** [comment]
> @wolfstudy Is this issue still need?

Yes, will close the issue
