### ISSUE TITLE
Support receive timeout

### ISSUE THREAD

**Issue by xujianhai666** [apache/pulsar-client-go#152]
**Is your feature request related to a problem? Please describe.**
be consistent with java consumer impl 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xujianhai666** [comment]
working on this now.

**Comment by wolfstudy** [comment]
> working on this now.

Cool, thanks for your contribution.

**Comment by cckellogg** [comment]
Doesn't the consumer already support a receive timeout? 

https://golang.org/pkg/context/#WithTimeout

You can create a context with a timeout and if that expires the receive will return.

**Comment by xujianhai666** [comment]
> Doesn't the consumer already support a receive timeout?
> 
> https://golang.org/pkg/context/#WithTimeout
> 
> You can create a context with a timeout and if that expires the receive will return.

@cckellogg yes, I impl with that.

**Comment by cckellogg** [comment]
@xujianhai666 Why do you need to add another method if you can already do it with current method Receive function?
