### ISSUE TITLE
The availablePermits of the topic is twice as much as the consumer.ReceiverQueueSize

### ISSUE THREAD

**Issue by dsmlily** [apache/pulsar-client-go#155]
@cckellogg @wolfstudy 
#### Expected behavior

They are equal

#### Actual behavior
The availablePermits of the topic is twice as much as the consumer.ReceiverQueueSize

#### Steps to reproduce

Occasional, not easy to reproduce

#### System configuration
**Pulsar version**: 2.4.0

**Comment by cckellogg** [comment]
Does the consumer stop receiving messages when this happens? It's possible this could happen if messages are batched by the producers. What is your average message size and rate that you are producing? Also how is your producer configured?

**Comment by dsmlily** [comment]
1、Just created the consumer and it happened. After that, the consumer could receive messages. 
2、The average message size is 250 byte and the rate is 1-3 messages /s
3、the producer is just configured the topic name

**Comment by cckellogg** [comment]
@dsmlily just to confirm you still receive messages as normal but the number of available permits is about double the queue size? Is that correct? Does the consumer ever stop receiving message?

**Comment by dsmlily** [comment]
@cckellogg 
1、just to confirm you still receive messages as normal but the number of available permits is about double the queue size? 
Yes, I still receive messages as normal but the number of available permits is about double the queue size.
2、Is that correct? 
If you refer to the message, yes, the message is correct.
3、Does the consumer ever stop receiving message?
the consumer has been running

today, I reproduce this, and find that the consumer reconnects broker every 90 seconds in blusar's logs, and the time is same as the connectedSince:

#####  1、broker's logs:
```
13:41:34.976 [pulsar-io-22-1] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /10.32.68.228:44686
13:42:35.081 [pulsar-io-22-3] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /10.32.68.228:44762
13:43:35.184 [pulsar-io-22-5] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /10.32.68.228:44842
13:45:05.299 [pulsar-io-22-7] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /10.32.68.228:44960

```

#####  2、topics stats：
```
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 2.6263857425095147,
  "msgThroughputOut" : 2382.13186845613,
  "averageMsgSize" : 0.0,
  "storageSize" : 3173,
  "publishers" : [ {
    "msgRateIn" : 0.0,
    "msgThroughputIn" : 0.0,
    "averageMsgSize" : 0.0,
    "producerId" : 8,
    "metadata" : { },
    "producerName" : "qa-pulsar-ali-27-0",
    "connectedSince" : "2020-01-03T11:00:41.272+08:00",
    "address" : "/10.32.32.223:52486"
  } ],
  "subscriptions" : {
    "response:10.32.68.228:8787:28065:1578020423793" : {
      "msgRateOut" : 2.6263857425095147,
      "msgThroughputOut" : 2382.13186845613,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 6,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Failover",
      "activeConsumerName" : "hgijd",
      "msgRateExpired" : 0.0,
      "consumers" : [ {
        "msgRateOut" : 2.6263857425095147,
        "msgThroughputOut" : 2382.13186845613,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "hgijd",
        "availablePermits" : 1017,
        "unackedMessages" : 0,
        "blockedConsumerOnUnackedMsgs" : false,
        "metadata" : { },
        "connectedSince" : "2020-01-03T13:45:05.3+08:00",
        "address" : "/10.32.68.228:44960"
      } ],
      "isReplicated" : false
    }
  },
  "replication" : { },
  "deduplicationStatus" : "Disabled"
}
```
