### ISSUE TITLE
Whether the error return value of Close() should be removed

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar-client-go#17]
In the go language, in general, we can't ignore the error, but in the `client`, `producer`, and `consumer` we ignore a lot of return values of the error type, are these return values necessary?

For example:

```
defer client.Close()
```

In many cases, we will use the above method to perform the `Close` operation. If the error of the close is negligible, we should remove the return value of the error in the interface definition.

**Comment by merlimat** [comment]
Good point. In general we try to do graceful close and return error if we fail. For close method we could just do forced close anyway if any problem occurs.
