### ISSUE TITLE
Not support multi pulsar cluster addresses

### ISSUE THREAD

**Issue by hailin0** [apache/pulsar-client-go#177]
**Is your feature request related to a problem? Please describe.**
not support the use of pulsar cluster addresses?

**Describe the solution you'd like**

```
client, err := pulsar.NewClient(pulsar.ClientOptions{
    URL: "pulsar://p1.pulsar.com:6650,pulsar://p2.pulsar.com:6650,pulsar://p3.pulsar.com:6650",
})
```

**Describe alternatives you've considered**

**Additional context**

**Comment by wolfstudy** [comment]
Thanks @hailin0 feedback.

Currently, the `go-client` not support multi URL in `NewClient()`.

**Comment by cgfork** [comment]
m

**Comment by keithnull** [comment]
@wolfstudy 

Hi, I'm interested in this issue (for OSPP Summer 2020) and willing to work on it. But I can't fully understand why multi pulsar cluster addresses are needed for a client.

In Pulsar's [doc](https://pulsar.apache.org/docs/en/concepts-architecture-overview/#service-discovery), service discovery section, I find that 

> Clients connecting to Pulsar brokers need to be able to communicate with an entire Pulsar instance using a single URL.

So why do we need multi cluster addresses in the client?

**Comment by ernado** [comment]
I was following this documentation:
http://pulsar.apache.org/docs/en/deploy-bare-metal/

There is
```env
brokerServiceurl=pulsar://host1:6650,host2:6650,host3:6650
```

Tried there with go client and got error:
```
dial tcp: address 10.0.0.4:6650,10.0.0.5:6650,10.0.0.3:6650: too many colons in address
```

So we need multiple addresses to support high availability deployments without DNS.
