### ISSUE TITLE
go1.13.5  the 1 error generated.

### ISSUE THREAD

**Issue by ghosts1995** [apache/pulsar-client-go#185]
#### Actual behavior

go: finding github.com/apache/pulsar/pulsar-client-go latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/crypto latest
# github.com/apache/pulsar/pulsar-client-go/pulsar
In file included from ../../pkg/mod/github.com/apache/pulsar/pulsar-client-go@v0.0.0-20200212225417-7cade481a1e0/pulsar/c_client.go:24:
./c_go_pulsar.h:22:10: fatal error: 'pulsar/c/client.h' file not found
#include <pulsar/c/client.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.

#### Steps to reproduce

go get -u -v github.com/apache/pulsar/pulsar-client-go/pulsar

#### System configuration
**Pulsar version**: x.y

Pulsar in matser version

go version go1.13.5 darwin/amd64

**Comment by cckellogg** [comment]
This is related to the c++ client which is located in this repo. 
https://github.com/apache/pulsar
https://pulsar.apache.org/docs/en/client-libraries-go/#requirements

This repo is for the native go client. To use the native client you can do this:
```
go get github.com/apache/pulsar-client-go/pulsar
```
