### ISSUE TITLE
Is this project support "if one pulsar broker dead,the request will request other brokers"

### ISSUE THREAD

**Issue by zxbfeng** [apache/pulsar-client-go#188]
when use client and the URL like this:"pulsar://us-west.example.com:6650",and the host "us-west.example.com" maps three ip:ip1,ip2,ip3, so when ip1 dead, can the client will not request ip1?
PS: when I use client, should it be global or local ?

**Comment by cckellogg** [comment]
What's the issue you are having? You should use the global one `pulsar://us-west.example.com:6650` and the client will end up connecting to the correct ip assuming they are all reachable by the client.

**Comment by wolfstudy** [comment]
@zxbfeng As @cckellogg said, will close this issue, If there is any problem please reopen it
