### ISSUE TITLE
Consumer Close() reports failure after Unsubscribe()

### ISSUE THREAD

**Issue by zzzming** [apache/pulsar-client-go#192]
#### Expected behavior
If Consumer Close() is called after Unsubscribe(), it will report error that `"server error: MetadataError: Consumer not found" name=consumer12 subscription=sharedsub0 topic="persistent://tenant/ns/topic"` Does it makes that once a consumer is unsubscribed, it should set the pc.state = consumerClosed so that internalClose() won't be sending BaseCommand_CLOSE_CONSUMER

#### Steps to reproduce

```
	if err := consumer.Unsubscribe(); err != nil {
		log.Errorf("", err)
	}
	consumer.Close()
```
#### System configuration
**Pulsar version**: 2.5.0
Latest golang library

**Comment by cgfork** [comment]
m
