### ISSUE TITLE
Add Tags to tag different versions of the GoLang Client for Versioning

### ISSUE THREAD

**Issue by afire007** [apache/pulsar-client-go#193]
**Is your feature request related to a problem? Please describe.**
This repository should tag older versions of the Pulsar Golang client

**Describe the solution you'd like**
Tag different versions so its easy to downgrade/upgrade using golang github plugin for managing dependencies

**Describe alternatives you've considered**
Currently I clone and tag the native pulsar library in order to tag older versions of the pulsar client. 

**Additional context**

**Comment by wolfstudy** [comment]
Thanks @afire007, Maybe we can create alpha tag in `pulsar-client-go`, convenient for users to downgrade/upgrade native Go Client.

@sijie What do you think of this suggestion?

**Comment by zzzming** [comment]
@wolfstudy @sijie Can we follow the go.mod tagging and versionning, https://blog.golang.org/publishing-go-modules ? Although not everyone has adopted go.mod, most projects have. With go mod v2 and major release, it may help us to align go client lib with any backward non-compatible Pulsar release. Thanks

**Comment by sijie** [comment]
@wolfstudy Can you start the email thread discussing releasing the first version of go client? I don't think we need to create an alpha tag.

@zzzming IMO the version should follow Pulsar's versioning convention.

**Comment by sijie** [comment]
The first release for the go client is released. close this issue.
