### ISSUE TITLE
test case for consumer SeekByTime

### ISSUE THREAD

**Issue by mileschao** [apache/pulsar-client-go#194]
Hi, 
Is it testify enough to not check published time for message in the test case for consumer [SeekByTime](https://github.com/apache/pulsar-client-go/blob/fc390a6a37f3cbd94ac46b3b5e4239b3ca5df875/pulsar/consumer_test.go#L823) ?
[test assert here](https://github.com/apache/pulsar-client-go/blob/fc390a6a37f3cbd94ac46b3b5e4239b3ca5df875/pulsar/consumer_test.go#L873) 
any idea?

**Comment by mileschao** [comment]
@sijie 
Hi, It seems that, `SeekByTime` will consume from the earliest message of a topic, whatever the time it is.

**Comment by sijie** [comment]
@mileschao - @wolfstudy can help look into this issue this week.

**Comment by wolfstudy** [comment]
> @mileschao - @wolfstudy can help look into this issue this week.

Sure, will try to reproduce and solve this issue

**Comment by mileschao** [comment]
> > @mileschao - @wolfstudy can help look into this issue this week.
> 
> Sure, will try to reproduce and solve this issue

I've try java client for seek by time, pulsar version 2.5.0.
The same problem.
so. I think it may be the bug of pulsar itself, not the client.

**Comment by wolfstudy** [comment]
> > > @mileschao - @wolfstudy can help look into this issue this week.
> > 
> > 
> > Sure, will try to reproduce and solve this issue
> 
> I've try java client for seek by time, pulsar version 2.5.0.
> The same problem.
> so. I think it may be the bug of pulsar itself, not the client.

Hello @mileschao when you use `seekByTime`, you should use `EventTime` or `PublishTime` of **ProducerMessages** struct to `seek`. 

Currently, the test case set time is longer, which is equivalent to seek to earliest, so you will see that messages are consumed from the beginning. If you want to consume messages from the specified time, you can seek to the specified `EventTime`.

**Comment by mileschao** [comment]
> > > > @mileschao - @wolfstudy can help look into this issue this week.
> > > 
> > > 
> > > Sure, will try to reproduce and solve this issue
> > 
> > 
> > I've try java client for seek by time, pulsar version 2.5.0.
> > The same problem.
> > so. I think it may be the bug of pulsar itself, not the client.
> 
> Hello @mileschao when you use `seekByTime`, you should use `PublishTime` of **Messages** interface to `seek`.
> 
> Currently, the test case set time is longer, which is equivalent to seek to earliest, so you will see that messages are consumed from the beginning. If you want to consume messages from the specified time, you can seek to the specified `PublishTime`.

@wolfstudy 
It is the `PublishTime` of message that have been used.
It seems whatever the time it is,  consumer will receive the message from the earliest.

just as comment I've noted before
> Hi, It seems that, `SeekByTime` will consume from the earliest message of a topic, whatever the time it is.

I think you can reproduce it :-)

**Comment by mileschao** [comment]
@wolfstudy 
Question:
If the `PublishTime`s of Messages are:
"2020-03-17T13:45:50-0400"
"2020-03-17T13:46:50-0400"
"2020-03-17T13:47:50-0400"

when I use the `SeekByTime(time time.Time)`, can I set time as "2020-03-17T13:46:40-0400"?
and, can I receive Messages with `PublishTime`s:
"2020-03-17T13:46:50-0400"
"2020-03-17T13:47:50-0400"

Thx for your time. :-)

**Comment by wolfstudy** [comment]
@mileschao Yes i reproduced this problem and i am fixing it thanks for your feedback

**Comment by mileschao** [comment]
> @mileschao Yes i reproduced this problem and i am fixing it thanks for your feedback

@wolfstudy :-)
Thx for your fixing.
Is this A bug of go client? or, pulsar server?

**Comment by wolfstudy** [comment]
@mileschao The bug will be fixed in https://github.com/apache/pulsar-client-go/pull/199, PTAL

**Comment by mileschao** [comment]
> @mileschao The bug will be fixed in #199, PTAL

@wolfstudy 
Thx for your quick fix. :-)
PR merge wanted.
