### ISSUE TITLE
Support ack timeout

### ISSUE THREAD

**Issue by hrsakai** [apache/pulsar-client-go#217]
> The ack timeout was intentionally left out from the Go client.
>  Negative ack are the preferred way to solve that problem and ack timeout should be regarded as legacy.

We want to know the detailed reason.
We are currently considering using go client.
Can't the client support both features?(ack timoout and negative ack)

cf. https://github.com/apache/pulsar-client-go/pull/197

**Comment by jiazhai** [comment]
@hrsakai  Put this into our backlog.

**Comment by wolfstudy** [comment]
> We want to know the detailed reason.

AckTimeout is actually a legacy problem, we can use nack instead. In many cases, it is hard for the application to handle the failure of processing a particular message. 

AckTimeout main issue with this approach is that the "timeout" is inherently associated with what the application processing is doing. How long should we set the `acktimeout`? In most cases, an ack-timeout of 1min is a perfectly good value, though if the processing takes 3min on average, that would trigger the redelivery of each message multiple times... hence, ack-timeout cannot be turned on by default.

**Comment by wolfstudy** [comment]
> We are currently considering using go client.

Welcome

**Comment by wolfstudy** [comment]
> @hrsakai Put this into our backlog.

@jiazhai The ack timeout was intentionally left out from the Go client.  Maybe we don't put this into our backlog

**Comment by hrsakai** [comment]
@wolfstudy 
Thank you for your explanation.
It makes sense to me.

**Comment by hrsakai** [comment]
We will consider using nack instead of ack timeout.

**Comment by wolfstudy** [comment]
@hrsakai Welcome, i will close this issue, If there are any problems, we can reopen it.

**Comment by shohi** [comment]
Is it possible to set timeout per Ack/Nack request, e.g. `Ack(timeout, message)? or even further to support context?

**Comment by merlimat** [comment]
The ack timeout referred here is not the timeout on the ack operation, rather the timeout on the application processing a message. 

Regardless, it was a mistake to add in Java API, and that’s why we didn’t add it in the new Go API. 

Negative acks are better because they convey the application intention on the outcome of processing a message. 

There’s no context or timeout on the ack/nack operations because these happen in background. 

If these fail, the message will be resent and the application will have the chance to ack/nack again.

**Comment by shohi** [comment]
@merlimat thanks very much for your patient and detailed explanation :-).  It makes sense to me.

**Comment by imqishi** [comment]
> The ack timeout referred here is not the timeout on the ack operation, rather the timeout on the application processing a message.
> 
> Regardless, it was a mistake to add in Java API, and that’s why we didn’t add it in the new Go API.
> 
> Negative acks are better because they convey the application intention on the outcome of processing a message.
> 
> There’s no context or timeout on the ack/nack operations because these happen in background.
> 
> If these fail, the message will be resent and the application will have the chance to ack/nack again.

hi, I want to know if there's no ack-timeout and consume exit without nack, when will the message be resent? If there's situation a long process message cause multiple retry?
