### ISSUE TITLE
Reader can not read new messages after subscribing with LatestMessageID

### ISSUE THREAD

**Issue by cornelk** [apache/pulsar-client-go#223]
#### Expected behavior

Reading of new messages is possible. 

#### Actual behavior

No message can be read.

#### Steps to reproduce

```
func TestReaderLatestMessageID(t *testing.T) {
	client, err := NewClient(ClientOptions{
		URL: lookupURL,
	})

	assert.Nil(t, err)
	defer client.Close()

	topic := newTopicName()
	ctx := context.Background()

	// create producer
	producer, err := client.CreateProducer(ProducerOptions{
		Topic:                   topic,
		DisableBatching:         false,
		BatchingMaxMessages:     4,
		BatchingMaxPublishDelay: 1 * time.Second,
	})
	assert.Nil(t, err)
	defer producer.Close()

	_, err = producer.Send(ctx, &ProducerMessage{
		Payload: []byte("hello-0"),
	})
	assert.NoError(t, err)

	reader, err := client.CreateReader(ReaderOptions{
		Topic:                   topic,
		StartMessageID:          LatestMessageID(),
		StartMessageIDInclusive: false,
	})

	assert.Nil(t, err)
	defer reader.Close()

	// Reader should yield no message since it's at the end of the topic
	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	msg, err := reader.Next(ctx)
	assert.Error(t, err)
	assert.Nil(t, msg)
	cancel()

	_, err = producer.Send(ctx, &ProducerMessage{
		Payload: []byte("hello-1"),
	})
	assert.NoError(t, err)

	ctx, cancel = context.WithTimeout(context.Background(), 5*time.Second)
	msg, err = reader.Next(ctx)
	assert.NoError(t, err)
	assert.NotNil(t, msg)
	cancel()
}
```

fails to read the last `hello-1` message:

```
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
```

**Comment by jiazhai** [comment]
looks like a bug @wolfstudy  to take a look.

**Comment by wolfstudy** [comment]
Thanks @cornelk  feedback,  @jiazhai maybe this is not a bug.

In the first send, we can't read the message, because the reader `StartMessageID` option is `LatestMessageID()`, so in the second send, this reader should also not receive messages, right?

Please refer to the following code:

```
reader1, err := client.CreateReader(ReaderOptions{
		Topic:                   topic,
		StartMessageID:          EarliestMessageID(),
		StartMessageIDInclusive: false,
	})

	ctx, cancel = context.WithTimeout(context.Background(), 5*time.Second)
	msg, err = reader1.Next(ctx)
	assert.NoError(t, err)
	assert.NotNil(t, msg)
	cancel()
```

**Comment by cornelk** [comment]
What would be code that makes use of `LatestMessageID()` and is able to read the `hello-1` message? 

I expect to be able to read `hello-1` as latest message somehow, since it's the latest message. Your code using `EarliestMessageID()` will read the `hello-0` message.

**Comment by wolfstudy** [comment]
@cornelk If you want to read the `hello-1` meaage, you should start the reader before sending the message

**Comment by wolfstudy** [comment]
> I expect to be able to read `hello-1` as latest message somehow, since it's the latest message. Your code using `EarliestMessageID()` will read the `hello-0` message.

You can refer to [here](https://github.com/apache/pulsar-client-go/blob/master/pulsar/reader_test.go#L115-L181)
