### ISSUE TITLE
send add timeout

### ISSUE THREAD

**Issue by yarthur1** [apache/pulsar-client-go#242]
#### Expected behavior

I want add timeout on producer send func, the send func need pass a context parameter，so I pass a WithTimeout context 

#### Actual behavior

I have test and find that the WithTimeout context seem not work on producer send func.The producer send func not return after timeout.

#### my code

`

	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()

	id, err := s.config.DcSyncProducer.Send(ctx, msg)
	if err != nil{
		...
	}
`
above Send func is interface Producer Send method
`

	// Send a message
	// This call will be blocking until is successfully acknowledged by the Pulsar broker.
	// Example:
	// producer.Send(ctx, pulsar.ProducerMessage{ Payload: myPayload })
	Send(context.Context, *ProducerMessage) (MessageID, error)

	// SendAsync a message in asynchronous mode
	// The callback will report back the message being published and
	// the eventual error in publishing
	SendAsync(context.Context, *ProducerMessage, func(MessageID, *ProducerMessage, error))

`

#### System configuration
Pulsar version: 2.5.0
pulsar-client-go: lastest

**Comment by WJL3333** [comment]
@sijie i want to help. please assign this to me

**Comment by WJL3333** [comment]
it seemds the context struct passed to the SendAsync func not used to judge if the send is already timeout

**Comment by merlimat** [comment]
Yes, it's currently only applied on retries. We should also check before sending

**Comment by sijie** [comment]
@WJL3333 - feel free to take this task.

**Comment by wolfstudy** [comment]
The #394 has achieved this function
