### ISSUE TITLE
Memory Leak zstdProvider.Decompress

### ISSUE THREAD

**Issue by rueian** [apache/pulsar-client-go#244]
The current implementation of `zstdProvider.Decompress` doesn't close the zstd decoder and will lead to memory leak.

https://github.com/apache/pulsar-client-go/blob/e7f1673350f208b5063823282d14906d70d66904/pulsar/internal/compression/zstd.go#L45-L60

There should be a `defer d.Close()` at line 50 according to the document: https://github.com/klauspost/compress/tree/master/zstd#usage-1

However, I would suggest just use the `decoder.DecodeAll` to implement `zstdProvider.Decompress` and reuse the decoder.

**Comment by sijie** [comment]
@goku321 is working on this issue.

**Comment by goku321** [comment]
@sijie Given that there's already a PR for this issue, Should I be working on this? 😅

**Comment by wolfstudy** [comment]
> @goku321 is working on this issue.

The task will be fixed in #245

**Comment by wolfstudy** [comment]
> @sijie Given that there's already a PR for this issue, Should I be working on this? 😅

Thanks @goku321
