### ISSUE TITLE
[Improve] Unified processing of error information in the project

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar-client-go#264]
Currently, there are some inconsistencies in the handling of errors. In order to ensure the structured output of the log, we should use withError() instead of Error().

E.g:

```
p.log.WithField("size", len(msg.Payload)).
	WithField("sequenceID", sequenceID).
	WithField("properties", msg.Properties).
	Error("unable to add message to batch")
```

```
if err != nil {
	log.WithError(err).Error("Failed to parse service URL")
	return nil, newError(ResultInvalidConfiguration, "Invalid service URL")
}
```

**Comment by wolfstudy** [comment]
@keithnull will track this task

**Comment by keithnull** [comment]
@wolfstudy 

I've checked all error-related logs, which can be classified as:

1. `.WithError(someErr).Error("some string")`
1. `.WithError(someErr).Error()`
1. `.Error("some string")`

Type 1 and 2 are exactly what we desire. For Type 3, if we want to make them unified, we need to define some `error` consts and use them instead, like:

```go
someErr := fmt.Errorf("some string")
// log.Error("some string")
log.WithError(someErr).Error()
```

But currently, existing errors are not very universal, i.e., they usually contain information specific to only a few situations. Therefore, maybe it's not quite necessary to do this now.
