### ISSUE TITLE
High cpu press because of the default BatchingMaxPublishDelay

### ISSUE THREAD

**Issue by LvBay** [apache/pulsar-client-go#265]
#### Expected behavior

When using the default configuration to create producers, it shows lower CPU usage

#### Actual behavior

When I create producers for two topics with 61 partitions, the CPU usage is high

#### Steps to reproduce

1. Create two topics with 61 partitions
2. Create failover producer with default configuration

#### System configuration
**Pulsar version**: docker image for latest

When I checked pprof, I set BatchingMaxPublishDelay to 1s, and the situation improved. But how much is the default value?

@wolfstudy

**Comment by LvBay** [comment]
How much better is the default value of BatchingMaxPublishDelay?

**Comment by sijie** [comment]
`batchMaxPublishDelay` will affect the publish latency. If your workload is latency-sensitive, you probably want to make sure the value is around milliseconds. Otherwise you will see huge publish latency.

**Comment by LvBay** [comment]
If I use Send() instead of SendAsync(), does it mean that batchMaxPublishDelay can be set larger without affecting publish latency? @sijie

**Comment by merlimat** [comment]
Yes, it will not affect the publish latency of `Send()` operations.

There are few possible improvements here: 
 1. Do not schedule the task until the first `SendAsync()` call
 2. Share the same ticker for multiple producers (maybe using a pool of them)

**Comment by LvBay** [comment]
> 2. Share the same ticker for multiple producers (maybe using a pool of them)
Agree with this

**Comment by kyrozetera** [comment]
> 1. Do not schedule the task until the first SendAsync() call
>2. Share the same ticker for multiple producers (maybe using a pool of them)

Have either of these options been pushed forward? This seems like a good idea, especially if SendAsync is used very sparingly, or if all producers have the same publish delay. All those tickers can eat up a lot of CPU for an idle service.
