### ISSUE TITLE
Is there any relationship between consumer throughput and ConsumerOptions.ReceiverQueueSize and ConsumerOptions.MessageChannel and the time required to process each message?

### ISSUE THREAD

**Issue by LvBay** [apache/pulsar-client-go#267]
For example, if the topic has 10 partitions, I need the consumer to achieve a throughput of 1000msg/s, and it takes 10ms to process each message. How can I set the value of ConsumerOptions?

**Comment by wolfstudy** [comment]
The `MessageChannel` is used to receive messages, all messages received by consumers will be filled into MessageChannel, the code example as follows:

```
channel := make(chan pulsar.ConsumerMessage, 100)

	options := pulsar.ConsumerOptions{
		Topic:            "topic-1",
		SubscriptionName: "my-subscription",
		Type:             pulsar.Shared,
	}

	options.MessageChannel = channel

	consumer, err := client.Subscribe(options)
	if err != nil {
		log.Fatal(err)
	}

	defer consumer.Close()

	// Receive messages from channel. The channel returns a struct which contains message and the consumer from where
	// the message was received. It's not necessary here since we have 1 single consumer, but the channel could be
	// shared across multiple consumers as well
	for cm := range channel {
		msg := cm.Message
		fmt.Printf("Received message  msgId: %v -- content: '%s'\n",
			msg.ID(), string(msg.Payload()))

		consumer.Ack(msg)
	}
```

The `ReceiverQueueSize` sets the size of the consumer to receive queue. It is a buffer of a channel in go language. Default value is 1000

**Comment by LvBay** [comment]
> For example, if the topic has 10 partitions, I need the consumer to achieve a throughput of 1000msg/s, and it takes 10ms to process each message. How can I set the value of ConsumerOptions?

Are there any best practices regarding this situation?

**Comment by sijie** [comment]
@LvBay 

If the consumer takes 10ms to process each message, it means that for a single thread you can process 100 messages/second. So you can have 10 threads to process messages to achieve 1000 msgs/second.

**Comment by LvBay** [comment]
> @LvBay
> 
> If the consumer takes 10ms to process each message, it means that for a single thread you can process 100 messages/second. So you can have 10 threads to process messages to achieve 1000 msgs/second.

Thanks.
