### ISSUE TITLE
undefined reference to `__fprint_chk`

### ISSUE THREAD

**Issue by georgewilk01** [apache/pulsar-client-go#274]
#### Expected behavior

go test command runs successfully when building with github.com/apache/pulsar-client-go@master on alpine

#### Actual behavior
go test fails with the following output:

`# github.com/valyala/gozstd
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/valyala/gozstd/libzstd_linux_amd64.a(zdict.o): in function `ZDICT_analyzeEntropy':
zdict.c:(.text+0x7ce): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/valyala/gozstd/libzstd_linux_amd64.a(zdict.o): in function `ZDICT_analyzePos':
zdict.c:(.text+0x1832): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: zdict.c:(.text+0x18c2): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/valyala/gozstd/libzstd_linux_amd64.a(zdict.o): in function `ZDICT_finalizeDictionary':
zdict.c:(.text+0x1b24): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/valyala/gozstd/libzstd_linux_amd64.a(zdict.o): in function `ZDICT_trainFromBuffer_unsafe_legacy':
zdict.c:(.text+0x1d54): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/valyala/gozstd/libzstd_linux_amd64.a(zdict.o):zdict.c:(.text+0x1dd4): more undefined references to `__fprintf_chk' follow
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/valyala/gozstd/libzstd_linux_amd64.a(entropy_common.o): in function `FSE_readNCount':
entropy_common.c:(.text+0x345): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/valyala/gozstd/libzstd_linux_amd64.a(fastcover.o): in function `FASTCOVER_buildDictionary.isra.6':
fastcover.c:(.text+0x3a9): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: fastcover.c:(.text+0x44f): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: fastcover.c:(.text+0x488): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/valyala/gozstd/libzstd_linux_amd64.a(fastcover.o): in function `FASTCOVER_ctx_init':
fastcover.c:(.text+0x8a0): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: fastcover.c:(.text+0x8e6): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/valyala/gozstd/libzstd_linux_amd64.a(fastcover.o):fastcover.c:(.text+0xbc7): more undefined references to `__fprintf_chk' follow
collect2: error: ld returned 1 exit status
The command '/bin/sh -c go test -mod=vendor ./...' returned a non-zero code: 2`

#### Steps to reproduce

Create project with pulsar-client-go dependency
go get github.com/apache/pulsar-client-go/pulsar@master
go mod tidy
go mod vendor
run go test -mod=vendor ./... on alpine docker image (golang:alpine)

#### System configuration
**Pulsar version**: apachepulsar/pulsar v2.5.2

**Comment by merlimat** [comment]
@georgewilk01 This is due to the library `github.com/valyala/gozstd` that provides pre-compiled binaries for linux but these won't work on Alpine. I already have a fix for that, will post it soon. Workaround, if you can, is to use `CGO_ENABLED=0`.
