### ISSUE TITLE
failed to create consumer with ReceiverQueueSize set to -1

### ISSUE THREAD

**Issue by shohi** [apache/pulsar-client-go#288]
#### Expected behavior

create the consumer successfully. According to the doc, ReceiverQueueSize set to `-1` only disables prefetching in consumer.

#### Actual behavior
Panic when creating consumer with the setting.

```
panic: makechan: size out of range
```

Test code
```go
func TestConsumer_NegativeQueueSize(t *testing.T) {
	client, err := pulsar.NewClient(pulsar.ClientOptions{
		URL: "pulsar://localhost:6650",
	})

	if err != nil {
		t.FailNow()
	}
	defer client.Close()

	consumer, err := client.Subscribe(pulsar.ConsumerOptions{
		Topic:             "topic",
		SubscriptionName:  "my-sub",
		ReceiverQueueSize: -1,
	})
	defer func() {
		if consumer != nil {
			consumer.Close()
		}
	}()

	if err != nil {
		t.FailNow()
	}
}
```

#### System configuration
**Pulsar version**: 2.5.2
**pulsar-client-go**: latest(861d7af)

**Comment by wolfstudy** [comment]
@shohi Sorry, this comment may be wrong, `receiveQueueSize` is essentially the size of golang channel buffer.  Can you help fix the issue?

**Comment by shohi** [comment]
Sure
