### ISSUE TITLE
Provide producer name

### ISSUE THREAD

**Issue by JoseFMP** [apache/pulsar-client-go#295]
According to Pulsar documentation, a message should have a "producer name":
![image](https://user-images.githubusercontent.com/24405049/85378157-5ffd1500-b564-11ea-8de0-31d5dd0d96c3.png)

However, in this library there is no way to get the producer name upon reception of a message.

It'd be lovely to have. What I want to do here is to avoid to read my own messages, so I would check who is the producer of a message and if is the same name as me, then I'd do not do anything with that message.

**Comment by wolfstudy** [comment]
@JoseFMP Thanks feedback, In `ProducerOptions` struct, we have provided the `Name` option to allow users to specify a name for a producer. If not assigned, the system will generate a globally unique name.

**Comment by JoseFMP** [comment]
@wolfstudy 
Sorry that is unrelated to my request.

My request is, according to Pulsar specs, a message carries as metadata the producer name. When I read a message, however, this pulsar go client, does not have implemented any way to retrieve the producer name. It'd be great to have.

Note this has nothing to do whether you have the option to add the name in the producer or not.

**Comment by merlimat** [comment]
@JoseFMP the `Message.getProducerName()` is already available in the other client libs and we have the info in the underlying protobuf metadata. It should be easy to expose that in the `Message` interface here. Do you want to give it a shot?
