### ISSUE TITLE
Should clear Error/Warn log

### ISSUE THREAD

**Issue by liangyuanpeng** [apache/pulsar-client-go#306]
#### Expected behavior

Got detail error message when connection failed.

#### Actual behavior

Just got `WARN[0000] Failed to perform initial handshake - Expecting 'Connected' cmd, got 'ERROR'   local_addr="192.168.1.11:49262" remote_addr="pulsar://192.168.1.11:6560"`

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

#### Other

connection.go#doHandshake
```
	if cmd.Connected == nil {
		c.log.Warnf("Failed to perform initial handshake - Expecting 'Connected' cmd, got '%s' ",
			cmd.Type)
		return false
	}
```

Can  we use `cmd.GetError().GetMessage()`     instead of  `cmd.Type` ? just like :  

```
	if cmd.Connected == nil {
		c.log.Warnf("Failed to perform initial handshake - Expecting 'Connected' cmd, got '%s' ",
			cmd.GetError().GetMessage())
		return false
	}
```

 and it can let me got `WARN[0000] Failed to perform initial handshake - Expecting 'Connected' cmd, got 'Unable to authenticate'  local_addr="192.168.1.11:50334" remote_addr="pulsar://192.168.1.11:6560"`. Maybe it should be `Error`   instead of  `Warn`.

**Comment by wolfstudy** [comment]
Thanks to @liangyuanpeng feedback. Can you send a pull request to fix the issue?

**Comment by liangyuanpeng** [comment]
@wolfstudy Yeah, i will. Thanks for your reply.
