### ISSUE TITLE
Talk about `send` interface logic 

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar-client-go#31]
**Is your feature request related to a problem? Please describe.**

In `Producer` interface, `Send` is defined as follows:

```
Send(context.Context, *ProducerMessage) error

SendAsync(context.Context, *ProducerMessage, func(MessageID, *ProducerMessage, error))
```

In fact, when the pulsar client receives the `sendReceipt`, we don't assign a value to the `ProducerMessage`. The returned value is always nil.

**Describe the solution you'd like**

We can define the interface as follows:

```
Send(context.Context, *ProducerMessage) (MessageID, error)

SendAsync(context.Context, *ProducerMessage, func(MessageID,  error))
```

This way, on the one hand, it can be consistent with the Java client in the interface definition. On the other hand, we only need the msgID field. In this regard, if there is a place that is not considered comprehensive, please correct me.

**Comment by merlimat** [comment]
👍 SGTM. It was a frequently requested feature on the C++  based Go client.

**Comment by merlimat** [comment]
We should do this before stabilizing the API

**Comment by jiazhai** [comment]
seems already get a conclusion. would like to close this issue
