### ISSUE TITLE
Some messages are missing when reopen consumer 

### ISSUE THREAD

**Issue by taiyang-li** [apache/pulsar-client-go#318]
## Expected behavior

Messages are consumed at least once when close and open consumer again.

## Actual behavior

Some messages are missing when reopen consumer 

### Producer
send 10k message per batch, every message in on batch has the same timestamp. 

send_to_pulsar.go 
``` go
func main() {
	if len(os.Args) < 2 {
		log.Fatal("./$0 speed")
	}

	speed, err := strconv.Atoi(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}

	client, err := pulsar.NewClient(pulsar.ClientOptions{
		URL: "pulsar://localhost:6650",
	})
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()

	producer, err := client.CreateProducer(pulsar.ProducerOptions{
		Topic: "mytopic",
	})
	if err != nil {
		log.Fatal(err)
	}
	defer producer.Close()

	for {
		t := time.Now().Unix()
		for i := 0; i < speed; i++ {
			msg := fmt.Sprintf(`{"number": "%d" , "time":  %d}`, i, t*1000)
			producer.Send(context.Background(), &pulsar.ProducerMessage{
				Payload: []byte(msg),
			})
		}
		time.Sleep(time.Second)
	}
}

```

Run producer
``` bash 
go build  -o send_to_pulsar
./send_to_pulsar 10000 
```

### Consumer 
Consumer messages from pulsar, and print in stdout. Every 2 minutes the consumer and client will be closed and opened again. 

recv_from_pulsar.go
```
func consume() {
	client, err := pulsar.NewClient(pulsar.ClientOptions{
		URL: "pulsar://localhost:6650",
	})
	if err != nil {
		log.Fatalln(err)
	}
	defer client.Close()

	consumer, err := client.Subscribe(pulsar.ConsumerOptions{
		Topic:            "mytopic",
		SubscriptionName: "mysub",
		Type:             pulsar.Shared,
	})
	if err != nil {
		log.Fatalln(err)
	}
	defer consumer.Close()

	ctx, cancel := context.WithCancel(context.Background())
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		for {
			msg, err := consumer.Receive(ctx)
			if err != nil {
				break
			}
			consumer.Ack(msg)
			fmt.Println(string(msg.Payload()))
		}
	}()

	time.Sleep(2 * time.Minute)
	consumer.Unsubscribe()
	time.Sleep(5 * time.Second)
	cancel()
	wg.Wait()
}

func main() {
	i := 0
	for {
		fmt.Println("start consume", i)
		consume()
		fmt.Println("finish consume", i)
	}
}

```

Run consumer: 
``` bash
go build -o recv_from_pulsar 
./recv_from_pulsar > data 
```

### Result 
Since all consumed messages are printed in `data` file,  run the command below to see if all messages are consumed. 
``` bash 
cat data | grep number   |  awk -F'[:}]'  '{print $3}' | awk  '{counts[$1]++} END{for (time in counts) print time, counts[time]}'  |  sort -k1 -n
```

 We expect message count with the same timestamp is 10k.  But the results are not as expected. The timestamps of missing messages are just near the time when consumer was reopend. 
![image](https://user-images.githubusercontent.com/8181003/86991322-5f55b700-c1d1-11ea-9c5d-ec7497e48f74.png)

## System configuration
Only one producer and one consumer 
pulsar: 2.5.1
pulsar-client-go: v0.1.1
Topic partition number: 14
Consume mode: Shard

**Comment by sijie** [comment]
@taiyang-li Are you running consumers before running producers?

**Comment by taiyang-li** [comment]
> @taiyang-li Are you running consumers before running producers?

Run producer first and then consumer

**Comment by taiyang-li** [comment]
> > @taiyang-li Are you running consumers before running producers?
> 
> Run producer first and then consumer
