### ISSUE TITLE
Support custom logger pulsar-client-go 

### ISSUE THREAD

**Issue by taiyang-li** [apache/pulsar-client-go#320]
**Is your feature request related to a problem? Please describe.** 
Currently, all logs of pulsar-client-go are printed in stderr as code below.
Maybe we can support user custom logger to print logs in other places, for example in files
``` go 
       consumer := &consumer{
		topic:                     topic,
		client:                    client,
		options:                   options,
		disableForceTopicCreation: disableForceTopicCreation,
		messageCh:                 messageCh,
		closeCh:                   make(chan struct{}),
		errorCh:                   make(chan error),
		dlq:                       dlq,
		log:                       log.WithField("topic", topic),
	}

func WithField(key string, value interface{}) *Entry {
	return std.WithField(key, value)
}
```

**Describe the solution you'd like**
Can we add a new method `SetLogger` for interface Consumer/Producer. In default case, logs are still printed in stderr. In other cases, print logs as the set logger. 

If you think it is OK, I'am glad to make some improvement for this problem.

**Comment by sijie** [comment]
@taiyang-li If you are interested in this feature, can you send out a pull request?

**Comment by taiyang-li** [comment]
> @taiyang-li If you are interested in this feature, can you send out a pull request?

I will try.

**Comment by wolfstudy** [comment]
@taiyang-li Currently, pulsar-client-go uses `logrus` lib, and supports the structured log output format, which is convenient for users to highly customize their own log format. You can encapsulate the corresponding program based on logrus in your own program, and customize the log output to any location you want

**Comment by wolfstudy** [comment]
Of course, the problem now is that we only support the logrus lib. Maybe we can encapsulate a `Logger()` interface to support users to access different log libs. About this issue, we already have an [issue](https:/ /github.com/apache/pulsar-client-go/issues/228) tracking this.

**Comment by wolfstudy** [comment]
@taiyang-li Can we close this issue, and track this issue in #228 ?
