### ISSUE TITLE
HasNext returns false when reading last message inclusive

### ISSUE THREAD

**Issue by quintans** [apache/pulsar-client-go#328]
#### Expected behavior

`Reader.HasNext()` should return true when when reading last message inclusive.

#### Actual behavior

`Reader.HasNext()` returns false.

#### Steps to reproduce

```go
package main

import (
	"context"
	"fmt"
	"testing"

	"github.com/apache/pulsar-client-go/pulsar"
	"github.com/stretchr/testify/assert"
)

const (
	lookupURL = "pulsar://localhost:6650"
	topic     = "persistent://public/default/test"
)

func TestReaderLatestInclusiveHasNext(t *testing.T) {
	client, err := pulsar.NewClient(pulsar.ClientOptions{
		URL: lookupURL,
	})

	assert.Nil(t, err)
	defer client.Close()

	ctx := context.Background()

	// create producer
	producer, err := client.CreateProducer(pulsar.ProducerOptions{
		Topic:           topic,
		DisableBatching: true,
	})
	assert.Nil(t, err)
	defer producer.Close()

	// send 10 messages
	var lastMsgID pulsar.MessageID
	for i := 0; i < 10; i++ {
		lastMsgID, err = producer.Send(ctx, &pulsar.ProducerMessage{
			Payload: []byte(fmt.Sprintf("hello-%d", i)),
		})
		assert.NoError(t, err)
		assert.NotNil(t, lastMsgID)
	}

	// create reader on the last message (inclusive)
	reader, err := client.CreateReader(pulsar.ReaderOptions{
		Topic:                   topic,
		StartMessageID:          pulsar.LatestMessageID(),
		StartMessageIDInclusive: true,
	})

	assert.Nil(t, err)
	defer reader.Close()

	var msgID pulsar.MessageID
	if reader.HasNext() {
		msg, err := reader.Next(context.Background())
		assert.NoError(t, err)

		assert.Equal(t, []byte("hello-9"), msg.Payload()) // updated after original post
		msgID = msg.ID()
	}

	assert.Equal(t, lastMsgID.Serialize(), msgID.Serialize()) // updated after original post
}
```

#### System configuration
**Pulsar version**: 2.6.0

**Comment by quintans** [comment]
seems relate to #241

**Comment by quintans** [comment]
Small update regarding the test. This test was created without having the actual feature.
If there is another approach to get the last message, please let me know.

**Comment by sijie** [comment]
@wolfstudy Can you take a look at this issue?

**Comment by wolfstudy** [comment]
> @wolfstudy Can you take a look at this issue?

Sure.

@quintans This question looks similar to #241, if we need to consume the message at the very beginning, we need to set the value of StartMessageID to `pulsar.EarliestMessageID()`

In the [reader_test](https://github.com/apache/pulsar-client-go/blob/master/pulsar/reader_test.go) file, we provide a variety of scenarios for reader use, which may be helpful to you

**Comment by quintans** [comment]
@wolfstudy It's the oposite. I need to consume the message at the very end. I want to read the last message sent to the topic.

**Comment by quintans** [comment]
@wolfstudy use case: If I send message m1, m2 and m3 to a topic t1, when my system restarts, I want to be able to read the last message sent to t1, in this case m3.
For what is worth, I submitted a PR https://github.com/apache/pulsar-client-go/pull/329 with a test case with what I am trying to achieve. (maybe not the best approach :grin: )

**Comment by wolfstudy** [comment]
> use case: If I send message m1, m2 and m3 to a topic t1, when my system restarts, I want to be able to read the last message sent to t1, in this case m3.

Thanks @quintans work for this, The current behavior is in line with expectations. When the consumer/reader restarts, the producer will continue to send messages during this period of time. At this time, the last message received by the reader is the message received from the topic after the reader has started successfully.

For example:

We start the reader first, and then start the producer. The producer sends four messages m0, m1, m2, and m3. At this time, the message received by the reader should be m0, m1, m2, m3. When the reader restarts for some reason, the producer sends the three messages m4, m5, and m6 during the restart period. Then when the reader is restarted, these three messages will not be received. But we can read the message by specifying a specific messageID.

```
	reader, err := client.CreateReader(ReaderOptions{
		Topic:          topic,
		StartMessageID: msgIDs[4],
	})
```

**Comment by quintans** [comment]
Thanks @wolfstudy for your explanation, but that is not the use case that I am trying to solve.
I have a `poller` service that is polling data from `system A` and then sending data to a topic t1, that eventually will be consumed by a `service B`. So `poller` is the producer and `service B` is the consumer.
`service A -> poller -> pulsar -> service B`
When `poller` service restarts I want to pick up from the last data that was successfully produced. To do that, the `poller` service needs to be able to read the last message from the topic t1.

**Comment by quintans** [comment]
Another way to to read the last message, was if we had a method `GetLastMessageID(topic)` that would return the last message ID, then I would just just use what the client already has.
example:
```go
	lastMsgID := client.GetLastMessageID(topic)
	reader, err := client.CreateReader(ReaderOptions{
		Topic:                   topic,
		StartMessageID:          lastMsgID,
		StartMessageIDInclusive: true, // important: I want to get the last message
	})
```
I wonder which would be more efficient...

**Comment by wolfstudy** [comment]
Maybe `HasNext() ` is a good way.

```
func (r *reader) HasNext() bool {
	if !r.lastMessageInBroker.IsZero() && r.hasMoreMessages() {
		return true
	}

	for {
		lastMsgID, err := r.pc.getLastMessageID()
		if err != nil {
			r.log.WithError(err).Error("Failed to get last message id from broker")
			continue
		} else {
			r.lastMessageInBroker = lastMsgID
			break
		}
	}

	return r.hasMoreMessages()
}
```

It will determine whether there is a next message based on getLastMessageID

**Comment by quintans** [comment]
Your tip seems to contradict the examples in [reader_test](https://github.com/apache/pulsar-client-go/blob/master/pulsar/reader_test.go) file. My test is basically a copy/paste of one of those.
I think you don't understand my use case :disappointed:.
My question is simple. Is it possible to get the latest (most recent) message in a topic (it does not matter if it was consumed or not)? How?
Can you have a look at this PR https://github.com/apache/pulsar-client-go/pull/329? maybe it helps understand what I am trying to do?

**Comment by quintans** [comment]
@wolfstudy did you had the time to look into this?

**Comment by quintans** [comment]
@wolfstudy this is the same situation described here for the java client https://github.com/apache/pulsar/issues/3162

**Comment by wolfstudy** [comment]
Sorry for the late reply. @quintans Exposing a `GetLastMessageID(topic string) MessageID` to the outside seems to be a more elegant way, and will not invade the current consumer more.

**Comment by quintans** [comment]
@wolfstudy I agree. Sould I create a ticket for this?

**Comment by quintans** [comment]
@wolfstudy even if exposing `GetLastMessageID` works for me, we still have the situation where calling
```go
	reader, err := client.CreateReader(pulsar.ReaderOptions{
		Topic:                   topic,
		StartMessageID:          pulsar.LatestMessageID(),
		StartMessageIDInclusive: true, // <-- has not effect
	})
```
does not return the last message.
Setting `StartMessageIDInclusive` to true, has no effect. Is this the expected behaviour?

**Comment by cornelk** [comment]
@quintans I had similar problems with this functionality in the past, I recreated this test in my alternative Pulsar-Go Client ( https://github.com/cornelk/pulsar-go ) to analyze the problem:

``` go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"testing"

	"github.com/cornelk/pulsar-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	lookupURL = "pulsar://localhost:6650"
	topic     = "persistent://public/default/test"
)

func TestReaderLatestInclusiveHasNext(t *testing.T) {
	l := log.New(os.Stderr, "", log.LstdFlags)
	client, err := pulsar.NewClient(lookupURL, pulsar.WithLogger(l))
	require.Nil(t, err)
	defer client.Close()

	ctx := context.Background()
	err = client.Dial(ctx)
	require.Nil(t, err)

	// create producer
	producer, err := client.NewProducer(ctx, pulsar.ProducerConfig{
		Topic:     topic,
		BatchSize: 1,
	})
	assert.Nil(t, err)
	defer producer.Close()

	// send 10 messages
	var lastMsgID *pulsar.MessageID
	for i := 0; i < 10; i++ {
		lastMsgID, err = producer.WriteMessage(ctx, []byte(fmt.Sprintf("hello-%d", i)))
		assert.NoError(t, err)
		assert.NotNil(t, lastMsgID)
	}

	// create reader on the last message (inclusive)
	reader, err := client.NewConsumer(ctx, pulsar.ConsumerConfig{
		Topic:                   topic,
		InitialPosition:         pulsar.LatestPosition,
		StartMessageIDInclusive: true,
	})

	require.Nil(t, err)
	defer reader.Close()

	msg, err := reader.ReadMessage(context.Background())
	require.NoError(t, err)

	assert.Equal(t, []byte("hello-9"), msg.Body) // updated after original post
	msgID := msg.ID

	require.NotNil(t, msgID)
	id1, err := lastMsgID.Marshal()
	id2, err := msgID.Marshal()
	assert.Equal(t, id1, id2) // updated after original post
}
```

The problem with your test code and my client was that after starting/subscribing the consumer, Pulsar was not done sending back the last message yet, which makes the `HasNext()` call fail. The solution for my client was to directly call `ReadMessage()`, which blocks until Pulsar sends the message back.
