### ISSUE TITLE
Multi Subscriptions with KeyShared type, received both messages, not to only one consumer

### ISSUE THREAD

**Issue by syklevin** [apache/pulsar-client-go#340]
#### Expected behavior

According to the docs of KeyShared type: `multiple consumer will be able to use the same subscription and all messages with the same key will be dispatched to only one consumer`

#### Actual behavior

Both consumers got all messages, with different message key

Tell us what happens instead

#### Steps to reproduce

```go

func TestPulsarPubsubWithSharedKey(t *testing.T) {
	cli, err := pulsar.NewClient(pulsar.ClientOptions{
		URL: "pulsar://localhost:6650",
	})
	if err != nil {
		t.Fatal(err)
	}

	topic := "topic-1"

	psr, err := cli.CreateProducer(pulsar.ProducerOptions{
		Topic: topic,
	})
	if err != nil {
		t.Fatal(err)
	}

	csr1, err := cli.Subscribe(pulsar.ConsumerOptions{
		Topic:            topic,
		SubscriptionName: "test-sub-1",
		Type:             pulsar.KeyShared,
	})
	if err != nil {
		t.Fatal(err)
	}

	csr2, err := cli.Subscribe(pulsar.ConsumerOptions{
		Topic:            topic,
		SubscriptionName: "test-sub-2",
		Type:             pulsar.KeyShared,
	})
	if err != nil {
		t.Fatal(err)
	}

	go func() {
		for {
			select {
			case cm := <-csr1.Chan():
				fmt.Println("csr1 received", string(cm.Payload()))
				cm.Ack(cm.Message)
			case cm := <-csr2.Chan():
				fmt.Println("csr2 received", string(cm.Payload()))
				cm.Ack(cm.Message)
			}
		}
	}()

	testPayload := []byte(`{"test": "1234565"}`)
	testPayload2 := []byte(`{"test": "246810"}`)

	ctx := context.Background()

	_, err = psr.Send(ctx, &pulsar.ProducerMessage{
		Key:     "test-msg-1",
		Payload: testPayload,
	})
	if err != nil {
		t.Fatal(err)
	}

	_, err = psr.Send(ctx, &pulsar.ProducerMessage{
		Key:     "test-msg-2",
		Payload: testPayload2,
	})
	if err != nil {
		t.Fatal(err)
	}

	time.Sleep(2 * time.Second)

}

```

How can we reproduce the issue

the output log shows

```sh

csr2 received {"test": "1234565"}
csr1 received {"test": "1234565"}
csr2 received {"test": "246810"}
csr1 received {"test": "246810"}

```

#### System configuration
**Pulsar version**: 2.6.0 docker standalone

**Comment by sijie** [comment]
@syklevin It seems like that you are using two different subscription names. Each subscription will receive a full copy of the messages. You need to use one same subscription name for your test.

**Comment by syklevin** [comment]
Just tested and it work as expected. Thanks for pointing out this magic part. It would be great if we could have more examples for different cases.

**Comment by syklevin** [comment]
@sijie BTW, how could we achieve Key_Shared with sticky hash range like java client?

**Comment by sijie** [comment]
@syklevin I don't think go client supports sticky hash range yet. Feel free to create a github issue for this feature. We can follow up on it.

**Comment by wolfstudy** [comment]
Close this issue, and https://github.com/apache/pulsar-client-go/issues/342 will track this task. Thanks @srkukarni feedback.
