### ISSUE TITLE
KeyShared with sticky hash range support

### ISSUE THREAD

**Issue by syklevin** [apache/pulsar-client-go#342]
**Is your feature request related to a problem? Please describe.**

go client should support this feature which is a useful for some user cases like scalable request-reply pattern.

**Describe the solution you'd like**

Add support for sticky hash range support like java client dose, let users decide which consumers should got the messages with key hash range.

**Additional context**

Related [issue](https://github.com/apache/pulsar/issues/7217) in java client for reference.

**Comment by wolfstudy** [comment]
@syklevin Are you interested in this feature? Always welcome to contribute this feature.
