### ISSUE TITLE
Messages should not be abstracted as interface for performance issue.

### ISSUE THREAD

**Issue by sundy-li** [apache/pulsar-client-go#346]
Well, in pulsar I saw messages are abstracted as an interface like 
```
type Message interface 
```

In golang, interfaces perform poor performances vs direct struct call. Here is the comparison.

https://syslog.ravelin.com/go-interfaces-but-at-what-cost-961e0f58a07b

**Comment by sijie** [comment]
@merlimat @wolfstudy Can you take a look at this?

**Comment by wolfstudy** [comment]
Yes, @sundy-li If struct can meet our needs, as you said, the performance of struct is better than the interface, and the usability is also higher. But in the implementation of go client, we have a `message` struct, and this struct implements the `Message` interface. At the same time, on the consumer side, we wrap a `ConsumerMessage` struct, which is a pair of a `Consumer` and `Message`, so In such a scenario, the interface may be more in line with our needs.

If you have better ideas, please feel free to discuss.

**Comment by sundy-li** [comment]
Well, I think
- You should consider the compatibility with the previous version of this client, maybe you should expose a new function.
- Other kafka clients like `sarama` and `kafka-go` , they always make the message to be a direct struct. This is very important for high throughput usage， although the interface may beneficial to good abstraction.

We can't use `ConsumerMessage`, because it's an interfaces too. 

We used to abstract the message in Kafka, the lag occurs， we can't afford the performance drawback.
![image](https://user-images.githubusercontent.com/3325189/90354189-15d37400-e07b-11ea-87b1-96443d1ea7cc.png)
