### ISSUE TITLE
ReceiverQueueSize -1 leads to crash

### ISSUE THREAD

**Issue by sneerin** [apache/pulsar-client-go#350]
#### Expected behavior
According to doc -1 is a correct value
Tell us what should happen

#### Actual behavior
App is crashing
Tell us what happens instead

#### Steps to reproduce
	options := pulsar.ConsumerOptions{
		Topic:             topic,
		SubscriptionName:  cg,
		Type:              pulsar.Shared,
		ReceiverQueueSize: -1,
	}

**Comment by jiazhai** [comment]
Thanks @sneerin for the reporting, We should add a check for value like "-1". Would you like to fix this issue?
