### ISSUE TITLE
Use dependency injection for log or use channel to expose

### ISSUE THREAD

**Issue by faceair** [apache/pulsar-client-go#370]
**Is your feature request related to a problem? Please describe.**
```go
import log "github.com/sirupsen/logrus"
p := &producer{
    options: options,
    topic:   options.Topic,
    client:  client,
    log:     log.WithField("topic", options.Topic),
}
```
This uses logrus.StandardLogger to create the entry, and the output format cannot be changed.
We don't use logrus in our business logic code, we have a custom log collection format. Now the pulsar-client-go logs interfere with the business logs in our process's stderr.

**Describe the solution you'd like**
We can learn sarama's error handling.
1. Define a log interface to allow user loggger injection. [sarama.go#L106](https://github.com/Shopify/sarama/blob/v1.27.0/sarama.go#L106)
2. return errors via the error channel and let the user print their own logs. [consumer_group.go#L416](https://github.com/Shopify/sarama/blob/v1.27.0/consumer_group.go#L416)、[consumer_group.go#L50](https://github.com/Shopify/sarama/blob/v1.27.0/consumer_group.go#L50)

**Comment by wolfstudy** [comment]
@faceair Good ideas, the https://github.com/apache/pulsar-client-go/pull/323 is trying to fix this.

**Comment by wolfstudy** [comment]
@faceair the #323 already merged into master, please help to check the feature.

**Comment by faceair** [comment]
Thank you very much. That's very nice. 👍
