### ISSUE TITLE
Problem with github.com/DataDog/zstd

### ISSUE THREAD

**Issue by omnilight** [apache/pulsar-client-go#379]
#### Expected behavior

Can use this library with other ones using datadog/zstd dependency

#### Actual behavior

During compilation I get error like:

case-insensitive import collision: "github.com/datadog/zstd" and "github.com/DataDog/zstd"

#### Steps to reproduce

1. Require `github.com/datadog/zstd` into your project or use some other library requiring it
2. Try to compile your code

As `pulsar-client-go` uses `github.com/DataDog/zstd` as it's import dependency under https://github.com/apache/pulsar-client-go/blob/master/pulsar/internal/compression/zstd_cgo.go, compilation fails.

#### System configuration
**pulsar-client-go**: v0.2.0

**Comment by wolfstudy** [comment]
@omnilight Maybe we can use `github.com/datadog/zstd` uniformly, which is more in line with the naming convention of the go community. Are you interested in sending a pull request to fix this issue?

**Comment by omnilight** [comment]
@wolfstudy Yes, I'm willing to help, will make PR

**Comment by omnilight** [comment]
@wolfstudy PR is created
