### ISSUE TITLE
99designs/keyring dependency causes build warnings on macOS Catalina

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar-client-go#380]
`github.com/apache/pulsar-client-go/oauth2/store` depends on `99designs/keyring` `v1.1.5`, which in turn depends on an older version of `github.com/keybase/go-keychain`, which throws deprecation warning error messages when building on MacOS. `v1.1.6` includes a fix for this, though it uses a replace directive to point to a fork of `go-keychain`, which itself is somewhat out of date:
https://github.com/99designs/keyring/issues/66

Consider updating to `v1.1.6` and keeping this bug open to track the dependency. When it no longer requires a replace directive, it is probably fine to close the issue.

**Comment by wolfstudy** [comment]
@zymap @EronWright Can you help to check the issue?
