### ISSUE TITLE
Update default router to switch partition on all batching thresholds

### ISSUE THREAD

**Issue by vergnes** [apache/pulsar-client-go#382]
**Is your feature request related to a problem? Please describe.**
The default router switches to another partition if the max delay to publish has elapsed but not for other threshold such as max number of messages or max number of bytes. The consequence is that even though there are multiple partitions this router does not leverage them. It is problematic when a partition is rate limited typically the router will continue to use the current partition until the max delay to publish has elapsed which impacts the overall performance.

**Describe the solution you'd like**
The solution is to update the default router to switch partition with one of the threshold is reached (number of messages, number of bytes, max delay to publish)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by wolfstudy** [comment]
The issue has been fixed in https://github.com/apache/pulsar-client-go/pull/383, will close it.
