### ISSUE TITLE
99designs/keyring causes build broken

### ISSUE THREAD

**Issue by Heasn** [apache/pulsar-client-go#384]
### enviorment
*os*:  macOS Catalina 10.15.6
*pulsar-client-go*: 0.2.0
*go*: go1.15.1 darwin/amd64

### problem
The dependency `99designs/keyring@v1.1.6` causes build broken, and the output is

```
go: found github.com/apache/pulsar-client-go/pulsar in github.com/apache/pulsar-client-go v0.2.0
# github.com/99designs/keyring
../../../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:136:8: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:181:9: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:181:21: undefined: keychain.Access
../../../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:187:9: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:187:21: undefined: keychain.Access
```

**Comment by raymondsugiarto** [comment]
Hi @Heasn ,

Lets try this:
1. Check your GOPATH..
2. Create a project inside your GOPATH, then create main.go and import pulsar there..
3. Run go get, (should be installing pulsar inside your src in GOPATH), wait until go pulsar client downloaded. Make sure code already download in src/github.com/apacher/pulsar like below

<img width="515" alt="Screen Shot 2020-11-05 at 18 09 41" src="https://user-images.githubusercontent.com/7098737/98233929-43e99580-1f92-11eb-8247-a6fd773f6b84.png">

4. Then use it inside GOPATH, or you can use it as usual, its up to you. Actually your go pulsar already downloaded in your GOPATH

Hopefully work for you

**Comment by Heasn** [comment]
thanks
