### ISSUE TITLE
Add ack timeout support

### ISSUE THREAD

**Issue by omnilight** [apache/pulsar-client-go#403]
Documentation says that there is an [Acknowledgement timeout](https://pulsar.apache.org/docs/en/concepts-messaging/#acknowledgement-timeout) in pulsar.

But I can not find and mentions of this options in subscriber config.

So, could you please describe, if go client supports that and, if not, what is default ack timeout?

**Comment by merlimat** [comment]
This was left out on purpose from the Go client lib. Ack timeout was the wrong solution we initially applied. Later we introduced negative Acks which are better suited for most of the cases (though we couldn't remove ack timeout for compatibility reasons there).

**Comment by omnilight** [comment]
Ok, so as I understood, no ack timeout anymore. But I think, that it must be described in pulsar docs... Anyway, thank you a lot, closing issue

**Comment by sagarrohankar-bsft** [comment]
> This was left out on purpose from the Go client lib. Ack timeout was the wrong solution we initially applied. Later we introduced negative Acks which are better suited for most of the cases (though we couldn't remove ack timeout for compatibility reasons there).

What if consumer crashed after consuming message but before ack/nack the message? Does broker redeliver in that case?

**Comment by frankjkelly** [comment]
> > This was left out on purpose from the Go client lib. Ack timeout was the wrong solution we initially applied. Later we introduced negative Acks which are better suited for most of the cases (though we couldn't remove ack timeout for compatibility reasons there).
> 
> What if consumer crashed after consuming message but before ack/nack the message? Does broker redeliver in that case?

Good question @merlimat do you know?

**Comment by RobertIndie** [comment]
> What if consumer crashed after consuming message but before ack/nack the message? Does broker redeliver in that case?

Yes. The broker will redeliver those messages when the consumer subscribes next time.

If the consumer does not ack/nack the messages, the subscription's position will not move forward. When the consumer fetches messages again, it will continue from where the subscription last stopped.

**Comment by frankjkelly** [comment]
> > What if consumer crashed after consuming message but before ack/nack the message? Does broker redeliver in that case?
> 
> Yes. The broker will redeliver those messages when the consumer subscribes next time.
> 
> If the consumer does not ack/nack the messages, the subscription's position will not move forward. When the consumer fetches messages again, it will continue from where the subscription last stopped.

Thanks for the clarification but I presume there is some delay between message delivery and redelivery (due to lack of an ack). If so is that defined by the golang consumer code or broker server-side?

**Comment by RobertIndie** [comment]
> Thanks for the clarification but I presume there is some delay between the initial message delivery and redelivery (due to lack of an ack). If so is that defined by the golang consumer code or broker server-side?

There is no delay in this case. When the consumer reconnects, the broker immediately delivers unacked messages.

**Comment by frankjkelly** [comment]
> There is no delay in this case. When the consumer reconnects, the broker immediately delivers unacked messages.

Ah maybe I was unclear - the Golang consumer remains connected and reading messages and a new consumer won't connect until either we autoscale and add a new pod or a pod terminates/restarts.

For our Java services the message is automagically redelivered after a fixed delay to (one of the shared) existing consumers regardless of consumer connection/reconnection.

**Comment by RobertIndie** [comment]
> For our Java services the message is automagically redelivered after a fixed delay to (one of the shared) existing consumers regardless of consumer connection/reconnection.

Maybe I get your points. Are you setting the AckTimeout of the Java consumer to a non-zero value(The default value is 0)? The java consumer will redelivery the messages after it can't ack the messages within the `ackTimeout`. This timeout is managed by the client-side code, not by the broker. However, the broker handles the redelivery logic, allowing it to resend messages to another consumer if necessary.

For the Go client, there is no AckTimeout configuration. Instead, message redelivery should be handled using either the NackBackoffPolicy or DLQPolicy.

**Comment by RobertIndie** [comment]
> I was talking about this Ack Timeout in the Java Consumer
https://github.com/codelipenghui/incubator-pulsar/blob/a7f9670402a54b99fbc7ac9717a837092cf444cf/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java#L63

I think this configuration has been deprecated in recent versions. And yes. The golang client is different. The golang doesn't have the ack timeout setting.

> if my various paths through the code don't result in an Ack or Nack
will the message be redelivered to existing consumers - it sounds like the answer is no.

No. You should either use `Nack` or `ReconsumeLater` to redelivery those messages.

**Comment by frankjkelly** [comment]
> > if my various paths through the code don't result in an Ack or Nack
> > will the message be redelivered to existing consumers - it sounds like the answer is no.
> 
> No. You should either use `Nack` or `ReconsumeLater` to redelivery those messages.

Thanks - A pity there's no way to have a `defer` block where I could inspect the message ack state and ensure it is acked or nacked. I probably just need to rewrite my code to have all the ack/nack handling in one place.

**Comment by RobertIndie** [comment]
> pity there's no way to have a `defer` block where I could inspect the message ack state and ensure it is acked or nacked. I probably just need to rewrite my code to have all the ack/nack handling in one place.

Does the [`redeliverUnacknowledgedMessages`](https://github.com/apache/pulsar/blob/59782b3c1f63baa68b2f5f33a33f1b00212159d7/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L483-L489) feature work for you? The Go client currently doesn't have this feature. But for this case, it seems worth supporting it. WDYT? @frankjkelly @merlimat

**Comment by frankjkelly** [comment]
> > pity there's no way to have a `defer` block where I could inspect the message ack state and ensure it is acked or nacked. I probably just need to rewrite my code to have all the ack/nack handling in one place.
> 
> Does the [`redeliverUnacknowledgedMessages`](https://github.com/apache/pulsar/blob/59782b3c1f63baa68b2f5f33a33f1b00212159d7/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L483-L489) feature work for you? The Go client currently doesn't have this feature. But for this case, it seems worth supporting it. WDYT? @frankjkelly @merlimat

I'm open to suggestions - I prefer the idea of the client handling the logic (a timeout - say default 30 seconds - where unacked messages are redelivered to the consumers) but if it's something I need to do explicitly I guess that's fine too.

**Comment by justinrixx** [comment]
>No. You should either use `Nack` or `ReconsumeLater` to redelivery those messages.

Is this the recommendation for handling errors from `Ack`? (processing is already complete, just failed to let the broker know that) As a newbie the docs led me to believe an ack timeout was the right way to handle this which is what led me to this issue.

I was particularly confused [when I found this issue](https://github.com/apache/pulsar/issues/3455) which uses `AckTimeout` but I couldn't find references to that field in the godoc, even going back to v0.1.0.
