### ISSUE TITLE
Impossible to install v0.3.0 because of zstd

### ISSUE THREAD

**Issue by dunglas** [apache/pulsar-client-go#440]
#### Expected behavior

It should be possible to install the latest version.

#### Actual behavior

PR #385 conflicts with other libs depending on `github.com/DataDog/zstd`. In my project, `zstd` is a transient dependency of many other open source dependencies, and all the other ones are using `github.com/DataDog/zstd`. This leads to an installation error:

    ../../go/pkg/mod/github.com/apache/pulsar-client-go@v0.3.0/pulsar/internal/compression/zstd_cgo.go:27:2: case-insensitive import collision: "github.com/datadog/zstd" and "github.com/DataDog/zstd"

Downgrading to v0.2.0 fixes the issue on the short term.

#### Steps to reproduce

`go get -u`

**Comment by freeznet** [comment]
should wait for https://github.com/golang/go/issues/26904 to allow `replace` like

```
replace github.com/DataDog/zstd v1.4.6-0.20200617134701-89f69fb7df32 => github.com/datadog/zstd v1.4.6-0.20200617134701-89f69fb7df32
```

**Comment by wuYin** [comment]
I have same issue, from pkg.go.dev statistics, `DataDog/zstd` is used much more often than `datadog/zstd`
Reference
https://pkg.go.dev/github.com/DataDog/zstd?tab=importedby
https://pkg.go.dev/github.com/datadog/zstd?tab=importedby   (pulsar-client-go is one of those few users)

**Comment by tuteng** [comment]
A temporary solution, if you don't need to use zstd related functions, you can simply replace this file and remove the code related to zstd, for example https://github.com/streamnative/pulsar-beat-output/blob/master/zstd_cgo.go

```
cp zstd_cgo.go /your-file-path/go/pkg/mod/github.com/apache/pulsar-client-go@v0.3.0/pulsar/internal/compression/zstd_cgo.go
```

**Comment by sunpe** [comment]
mark

**Comment by omnilight** [comment]
Anyway, data dog had added go.mod file to their library, so I believe, we can update dependency here too
