### ISSUE TITLE
Some error results are commented

### ISSUE THREAD

**Issue by jonyhy96** [apache/pulsar-client-go#444]
#### Expected behavior

Uncomment the error result

#### Actual behavior

https://github.com/apache/pulsar-client-go/blob/master/pulsar/error.go#L42-L73

Some error results are commented

If there is any specific reason that these error results has to be commented?

**Comment by jonyhy96** [comment]
Besides these errors are unexported, we can't assert errors use errors.Is in client side. Perhaps these errors should be export in error.go and use newError to create one?

**Comment by freeznet** [comment]
hi @jonyhy96, i agree with your point. should complete `func getResultStr(r Result) string` first and use `newError` to export the needed errors.

**Comment by jiazhai** [comment]
Thanks for @jonyhy96  and @freeznet for the root cause of this issue, mark this as help wanted, so anyone would like to contribute could help on this.
