### ISSUE TITLE
Support Large Message Size (PIP-37 / "chunking")

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar-client-go#456]
Currently the go client does not seem to support [PIP-37](https://github.com/apache/pulsar/wiki/PIP-37:-Large-message-size-handling-in-Pulsar) which allows for messages to be sent that are larger than the maximum message size by breaking them up on the producer side and re-assembling them in the consumer. This would be a handy feature to have parity with the [Java client](https://github.com/apache/pulsar/pull/4400)

**Comment by geniusjoe** [comment]
@RobertIndie Since chunk feature supported in v0.10 #805 , can we close this issue as completed?
