### ISSUE TITLE
Error when running on ARM32 bits - Raspberry Pi 2

### ISSUE THREAD

**Issue by hugomcruz** [apache/pulsar-client-go#485]
Hi, 

I am getting this error when I compile for the RPI2. 

panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x25f8c14, 0x1, 0x0, 0x1, 0x24180a8)
	/usr/local/go/src/runtime/internal/atomic/asm_arm.s:233 +0x14
github.com/apache/pulsar-client-go/pulsar/internal.(*rpcClient).NewRequestID(0x25f8c00, 0x24180a8, 0x2472090)
	/Users/hcruz/go/pkg/mod/github.com/apache/pulsar-client-go@v0.4.0/pulsar/internal/rpc_client.go:166 +0x34
github.com/apache/pulsar-client-go/pulsar.(*client).TopicPartitions(0x25a0c60, 0x25e40c0, 0x29, 0x1c17c, 0x1c944, 0x2472060, 0x30, 0x24)
	/Users/hcruz/go/pkg/mod/github.com/apache/pulsar-client-go@v0.4.0/pulsar/client_impl.go:166 +0x6c
github.com/apache/pulsar-client-go/pulsar.(*producer).internalCreatePartitionsProducers(0x2688000, 0x0, 0x0)
	/Users/hcruz/go/pkg/mod/github.com/apache/pulsar-client-go@v0.4.0/pulsar/producer_impl.go:149 +0x58
github.com/apache/pulsar-client-go/pulsar.newProducer(0x25a0c60, 0x2682000, 0x54b444, 0x24ba0e8, 0x6189f0)
	/Users/hcruz/go/pkg/mod/github.com/apache/pulsar-client-go@v0.4.0/pulsar/producer_impl.go:123 +0x264
github.com/apache/pulsar-client-go/pulsar.(*client).CreateProducer(0x25a0c60, 0x25e40c0, 0x29, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/hcruz/go/pkg/mod/github.com/apache/pulsar-client-go@v0.4.0/pulsar/client_impl.go:135 +0x50
main.createProducer(0x6f7544, 0x25a0c60, 0x2596cb8, 0x6, 0x25e40c0, 0x29, 0x25da800, 0x1fb, 0x25be1e0, 0x4e, ...)
	/Users/hcruz/Documents/GitHub/dump1090-tcm/publisher/pulsar.go:38 +0xa4
main.main()
	/Users/hcruz/Documents/GitHub/dump1090-tcm/publisher/main.go:164 +0x56c

The code just works fine in my mac, but fails when creating a producer on this line:

	producer, err := client.CreateProducer(pulsar.ProducerOptions{
		Topic: configuration.PulsarTopic,
	})

Any clues, or a RPI would not be supported at all?

**Comment by merlimat** [comment]
This looks more like a GO std library issue with `atomic.Xadd64()`.

**Comment by merlimat** [comment]
It seems related to https://github.com/golang/go/issues/23345 . Not sure if there is an easy workaround that can applied to avoid the issue.

**Comment by hugomcruz** [comment]
Yeh. I fixed it with a work around. 
By adding "padding" to align the 64 bits Uint64 it solved the problem.  For now, I fixed just for the producer by changing the files:

- rpc_client.go

type rpcClient struct {
	requestIDGenerator  uint64
	producerIDGenerator uint64
	consumerIDGenerator uint64
	**pad                 uint32**
	serviceNameResolver ServiceNameResolver
	pool                ConnectionPool
	requestTimeout      time.Duration
	log                 log.Logger
	metrics             *Metrics
}

- producer_partition.go

type partitionProducer struct {
	state  ua.Int32
	client *client
	topic  string
	log    log.Logger
	cnx    internal.Connection

	options             *ProducerOptions
	producerName        string
	producerID          uint64
	**pad                 uint32**
	batchBuilder        internal.BatchBuilder
	sequenceIDGenerator *uint64
	batchFlushTicker    *time.Ticker
.... (strut has more variables)

Now I have my producer code running fine in the Raspberry Pi 2.

**Comment by shoothzj** [comment]
@hugomcruz Would you mind contribute your fix to the community? It looks useful for ARM32 users. :)

**Comment by hugomcruz** [comment]
I haven't used this for a while. My message described the changes you need to do to run on ARM32. Proposing a commit to the main branch could have an impact in other platforms, so I am not sure this is a good idea.

**Comment by shoothzj** [comment]
closed by #1286
