### ISSUE TITLE
error not return when encode failed 

### ISSUE THREAD

**Issue by oryx2** [apache/pulsar-client-go#490]
Producer eat the error when scheme codec encode message failed,  ,should we just throw it?
[https://github.com/apache/pulsar-client-go/pulsar/producer_partition.go#L337](https://github.com/apache/pulsar-client-go/blob/5fb7f55939e6f4ec28126339b22a6b4018c0f2fa/pulsar/producer_partition.go#L337)

**Comment by stulzq** [comment]
I think it should output an error log, otherwise users will never know.
