### ISSUE TITLE
Producer block may block forever

### ISSUE THREAD

**Issue by jonyhy96** [apache/pulsar-client-go#491]
#### Expected behavior

If producer.Close are called,it will close within configured OperationTimeout

#### Actual behavior

producer.Close may block forever and won't time out after configured OperationTimeout

#### Steps to reproduce

Just run the perf program for a while and send SIGINT or ctrl+c to it. This situation may be triggered.

This is because the callback of [producer.SendAsyc](https://github.com/apache/pulsar-client-go/blob/master/perf/perf-producer.go#L132) contains a send behavior on a channel which under the same scope with [stopCh](https://github.com/apache/pulsar-client-go/blob/master/perf/perf-producer.go#L145-L162). When we trigger producer.Close, if `case <-stop:` happens before `case latency := <-ch:`, it will block forever because it may be block at [here](https://github.com/apache/pulsar-client-go/blob/master/pulsar/producer_partition.go#L700) and [RequestOnCnx](https://github.com/apache/pulsar-client-go/blob/master/pulsar/internal/rpc_client.go#L146-L165) has no time out guarantee.

#### System configuration
**Pulsar version**: any

**Comment by jonyhy96** [comment]
/cc @freeznet @wolfstudy 
I would like to fix this bug by add time out guarantee on RequestOnCnx
BTW, Can i join the slack of this project to get in touch with the mainainers?

**Comment by freeznet** [comment]
@jonyhy96 thanks, PR are always welcome ;)

Also, the slack is free to join:

> The Slack instance is at https://apache-pulsar.slack.com/
> You can self-register at https://apache-pulsar.herokuapp.com/

And you can join #dev-go channel to get in touch with go devs and users.

**Comment by jonyhy96** [comment]
https://apache-pulsar.slack.com/ shows me  `hy352144278@gmail.com doesn’t have an account on this workspace.` and https://apache-pulsar.herokuapp.com/ seems doesn't have #dev-go channel :sweat_smile:

**Comment by freeznet** [comment]
@jonyhy96 You can browse all available channels from the plus icon next to `Channels` dropdown item on your Slack. Also I have sent an invitation to your email `hy352144278@gmail.com` as well.
