### ISSUE TITLE
Make Topic Level Prometheus Metrics Optional

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar-client-go#500]
**Is your feature request related to a problem? Please describe.**
In `0.4.0`, https://github.com/apache/pulsar-client-go/pull/410 introduced topic level prometheus metrics. When consuming from or publishing to many topics, this creates many metrics and can cause problems for applications and/or prometheus instances. In my case, I saw up to 900k metrics produced by a single client, which caused memory problems in my application and temporarily brought down my prometheus server.

**Describe the solution you'd like**
I would like to be able to enable or disable the topic level metrics. I think these topic level metrics should be disabled by default, since that was the previous behavior.

**Describe alternatives you've considered**
I looked into the code introduced in `0.4.0`, and I don't see any ways to prevent these metrics from being created currently.

**Additional context**
I like the metrics I get out of the client in `0.3.0`. I think it's great to have them out of the box.

Also, the cardinality of metrics is preventing me from upgrading my go client from `0.3.0` to `0.4.0`.

**Comment by michaeljmarshall** [comment]
@merlimat - I notice that you created the metrics in https://github.com/apache/pulsar-client-go/pull/410. Do you have any thoughts on adding this feature and if so, how hard it would be to implement? Thanks!

**Comment by michaeljmarshall** [comment]
@wolfstudy - are you able to help provide insight into this feature request?

**Comment by merlimat** [comment]
@michaeljmarshall Missed your comment earlier. I don't think it would be hard to add the configuration. 

We'd just need some kind of enum setting in the `ClientOptions` to select the appropriate level of metric. 

Right now the labels selected are: https://github.com/apache/pulsar-client-go/blob/ec40d795841b1d61f7cbb07fad08e3c587db8801/pulsar/internal/metrics.go#L24

I believe, with just few adjustments it should be possible disable different labels. 
Eg:  we could have an enum like : 

```go
type MetricsCardinality int

const (
	Namespace MetricsCardinality = iota // Default value
	Tenant
	Topic
        None
)
```

**Comment by michaeljmarshall** [comment]
@merlimat - no worries, thank you for your helpful response. That makes sense, and it'll be great to get it in `0.5.0`.
