### ISSUE TITLE
Catch up Java client function list

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar-client-go#52]
**Non-Support Features:**

- [ ] Schema
- [ ] seek by time
- [x] nack
- [ ] replication
- [ ] Interceptor
- [ ] DeadLetterPolicy
- [x] receive with timeout
- [x] multi topics
- [x] topics pattern
- [ ] auto update partitions
- [ ] read compact
- [x] auth

**Comment by jiazhai** [comment]
@wolfstudy Is this updated with latest master?

**Comment by wolfstudy** [comment]
will close this issue, and track them in other pull request

**Comment by snowcrumble** [comment]
Is there any plan for Interceptor?

**Comment by wolfstudy** [comment]
> Is there any plan for Interceptor?

The feature LGTM+1, @snowcrumble If you are interested in this, can you send a pull request to impl this?

**Comment by snowcrumble** [comment]
> > Is there any plan for Interceptor?
> 
> The feature LGTM+1, @snowcrumble If you are interested in this, can you send a pull request to impl this?

OK, I would like to develop this.

**Comment by oginskis** [comment]
Is there a plan to support Pulsar Schema Registry? Maybe anyone is working on that already?

**Comment by wolfstudy** [comment]
> Is there a plan to support Pulsar Schema Registry? Maybe anyone is working on that already?

@keithnull is working for this task

**Comment by merlimat** [comment]
@wolfstudy @keithnull is there any design doc to share at this moment?

**Comment by oginskis** [comment]
@keithnull @wolfstudy Any estimates when that could be merged in?

**Comment by wolfstudy** [comment]
Sorry, @merlimat @oginskis About design doc of schema, not yet. The initial idea is to use the schema processing logic in the cgo client. In terms of implementation, I personally prefer to expose the schema as an option of `producerOptions` and `consumerOptions` rather than as a separate interface

**Comment by wolfstudy** [comment]
@merlimat @oginskis this is the Schema Registry design doc for Go Client, please take a look: https://gist.github.com/wolfstudy/e0c9b349cd405715a9e04dd8658510bc

**Comment by longtengz** [comment]
Any news on the **read compact** feature? This thread had been dead since a year ago. I assume there may be some roadblock to implementing the feature?
