### ISSUE TITLE
Sometime goroutine send message with timeout option ,but it be blocked

### ISSUE THREAD

**Issue by jiangbo9510** [apache/pulsar-client-go#527]
pulsar-client-version: v0.5.0

![image](https://user-images.githubusercontent.com/17549520/119365527-94cc9b80-bce2-11eb-98cd-8d33514a188b.png)

I have some question in line 493. Is this should be 

`item := p.pendingQueue.Peek()` ?

**Comment by xiebei1108** [comment]
I met same problem( pulsar-client-go v0.4.1).
Metrics pulsar_client_producer_pending_messages is always 58 and log in line 488 printed 58 times. So, I think send message timeout will block the goroutine. 
<img width="1164" alt="wecom-temp-f01895dd2cdef150eed33073f827de84" src="https://user-images.githubusercontent.com/28754442/119455796-87f48a00-bd6c-11eb-8e0d-ea340fb2b88d.png">

**Comment by jiangbo9510** [comment]
> I met same problem( pulsar-client-go v0.4.1).
> Metrics pulsar_client_producer_pending_messages is always 58 and log in line 488 printed 58 times. So, I think send message timeout will block the goroutine.
> <img alt="wecom-temp-f01895dd2cdef150eed33073f827de84" width="1164" src="https://user-images.githubusercontent.com/28754442/119455796-87f48a00-bd6c-11eb-8e0d-ea340fb2b88d.png">

I do't think so.  In my log, It not always 58, and It not always the same number.

**Comment by jiangbo9510** [comment]
Polling a item for pendingqueue will lost this one. Also  connection  recive the response from broken. It will not call the callback function. That's make the sending goroutine blocked on `wg.Wait()`

**Comment by wolfstudy** [comment]
> Polling a item for pendingqueue will lost this one. Also connection recive the response from broken. It will not call the callback function. That's make the sending goroutine blocked on `wg.Wait()`

@jiangbo9510 It looks like a bug here, can you send a pull request to fix this? welcome.

**Comment by jiangbo9510** [comment]
> > Polling a item for pendingqueue will lost this one. Also connection recive the response from broken. It will not call the callback function. That's make the sending goroutine blocked on `wg.Wait()`
> 
> @jiangbo9510 It looks like a bug here, can you send a pull request to fix this? welcome.

ok. I will send a pr in recent days.

**Comment by jiangbo9510** [comment]
If you have the same problem, You can replace the plusar-client-go library to https://github.com/jiangbo9510/pulsar-client-go/releases/tag/v0.5.2 in go mod file.

**Comment by jiangbo9510** [comment]
It fixed
