### ISSUE TITLE
Send gorutine blocked 

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar-client-go#565]
#### Expected behavior

In `blocking_queue.go`, 

```
func (bq *blockingQueue) Put(item interface{}) {
	bq.mutex.Lock() // 1. add the lock
	defer bq.mutex.Unlock()

	for bq.size == bq.maxSize {
		bq.isNotFull.Wait()
	}
        ...
}
```

when `bq.size == bq.maxSize`, It means that the pending queue is full at this time, and we use `bq.isNotFull.Wait()` to block the send gorutine here. At this point, we look forward to using `peek()` or other methods to consume the data from the pending queue, but here is a lock added. In fact, after blocking, we have not unlocked yet, so deadlock will occur here.

The peek() logic:

```
func (bq *blockingQueue) Peek() interface{} {
	bq.mutex.Lock() // 2. Try again to add the lock
	defer bq.mutex.Unlock()

	if bq.size == 0 {
		return nil
	}
	return bq.items[bq.headIdx]
}
```

Therefore, when the following logic is triggered, send gorutine will be blocked due to deadlock

```
	for bq.size == bq.maxSize {
		bq.isNotFull.Wait()
	}
```

#### Actual behavior

Tell us what happens instead

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

**Comment by cckellogg** [comment]
Do you have any profiling that shows go routines deadlocked here? Calling `Wait()` should release the lock right?

**Comment by wolfstudy** [comment]
> Calling Wait() should release the lock right?

Yes, When entering the `Wait()` phase, we should try to release the `Lock` so that subsequent gorutine can continue to operate this resource.

**Comment by cckellogg** [comment]
This code `bq.isNotFull` is a conditional variable (https://pkg.go.dev/sync#Cond.Wait) so it should already be releasing the lock when wait is called.

```
bq.isNotEmpty = sync.NewCond(&bq.mutex)
bq.isNotFull = sync.NewCond(&bq.mutex)
```

**Comment by wolfstudy** [comment]
> There might be another cause for this blocking? It there a way to reproduce this or get a profile of the the go routines when this happens?

Yes, it may also be caused by other places. There is no good way to reproduce this problem.
