### ISSUE TITLE
Some bugfix should to make a new tag

### ISSUE THREAD

**Issue by jiangbo9510** [apache/pulsar-client-go#578]
for example this one. https://github.com/apache/pulsar-client-go/pull/576
It already affecting usage.

**Comment by wolfstudy** [comment]
@jiangbo9510  Thanks for your suggestion. We will not tag this modification separately because of a bug fix, which will break our established time-based release agreement. In fact, for this situation, we can use the master branch as a temporary tag, which is allowed in go
