### ISSUE TITLE
Duplicate producer when create producer timeout

### ISSUE THREAD

**Issue by freeznet** [apache/pulsar-client-go#584]
When the broker or zookeeper is temporary offline, which will cause the producer timeout and re-connect to the broker. But if the broker has already done the previous create producer request, the reconnection will fail with an "already connected" error.

https://github.com/apache/pulsar/pull/5571 has addressed this issue in Java client, but go client still encounter this issue.

https://github.com/apache/pulsar-client-go/pull/582 add epoch to go client to solve this issue.

**Comment by cckellogg** [comment]
Addressed in #582
