### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by louishlz** [apache/pulsar-client-go#595]
https://github.com/apache/pulsar-client-go/blob/6426d39af9bcf3de44b155afc3eece56069b4a2b/pulsar/producer_impl.go#L193

oldNumPartitions should check the range!

**Comment by liangyuanpeng** [comment]
It's correct.

**Comment by wolfstudy** [comment]
The issue will be fixed in https://github.com/apache/pulsar-client-go/pull/598
