### ISSUE TITLE
why you have "github.com/99designs/keyring"? It cause problems in higher version of MacOS 11.4 for now

### ISSUE THREAD

**Issue by llqgit** [apache/pulsar-client-go#607]
#### Expected behavior

Should not show the deprecated error msg.

#### Actual behavior

![image](https://user-images.githubusercontent.com/8063914/131521462-81144da3-4238-4baa-899b-c7e2374edd01.png)

#### Steps to reproduce

Run with pulsar-client-go on MacOS with M1 silicon and version 11.4

#### System configuration
**Pulsar version**: 2.7.2
**Pulsar client go**: 0.6.0

**Comment by liangyuanpeng** [comment]
@llqgit  Repeat issue https://github.com/apache/pulsar-client-go/issues/626 , Cloud you close this?

**Comment by llqgit** [comment]
thx
