### ISSUE TITLE
Fix Godoc

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar-client-go#652]
The godoc throughout much of the project is incorrect, leading to IDEs such as VsCode not showing documentation unless the comment (accidentally?) starts with the correct identifier name. For example, when I'm creating a consumer, I can't see anything about what the different fields in `pulsar.ConsumerOptions`. For example, `Topic` shows nothing:
![image](https://user-images.githubusercontent.com/926884/139130968-f6b5f821-3131-4ca5-b13a-8f81caaa580b.png)
because the godoc at the definition (which is very useful), does not start with the string `Topic`:
![image](https://user-images.githubusercontent.com/926884/139131092-2103bdfd-316b-4edb-a94d-1dbee6c549c5.png)

Whereas `pulsar.Shared` does:
![image](https://user-images.githubusercontent.com/926884/139131536-87d1e3e3-6663-4e0a-8725-c6a86f66495b.png)
Because the comment happens to begin with the string `Shared`
![image](https://user-images.githubusercontent.com/926884/139131668-cb47851b-a425-4350-ba5a-80d33ca77e77.png)

**Comment by wolfstudy** [comment]
Thanks @flowchartsman and sounds good, If you are interested, welcome to send a pr to fix this problem.
