### ISSUE TITLE
Go client does not compile 

### ISSUE THREAD

**Issue by juiceppe** [apache/pulsar-client-go#679]
#### Expected behavior
When trying to install the client the output from:

`go get -u "github.com/apache/pulsar-client-go/pulsar"`

is 

`go: downloading golang.org/x/sys v0.0.0-20211124211545-fe61309f8881
go: downloading github.com/apache/pulsar-client-go/oauth2 v0.0.0-20211130045649-53d9c28dd3e8
go: downloading golang.org/x/net v0.0.0-20211201190559-0a0e4e1bb54c
 github.com/99designs/keyring
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:55:8: query.SetMatchSearchList undefined (type keychain.Item has no field or method SetMatchSearchList)
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:55:28: undefined: keychain.NewWithPath
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:115:34: undefined: keychain.Keychain
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:124:12: queryItem.SetMatchSearchList undefined (type keychain.Item has no field or method SetMatchSearchList)
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:136:8: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:146:9: undefined: keychain.Keychain
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:166:9: kcItem.UseKeychain undefined (type keychain.Item has no field or method UseKeychain)
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:181:9: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:181:21: undefined: keychain.Access
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:267:36: undefined: keychain.Keychain
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:181:21: too many errors`

#### System configuration
MacOS Big Sur 11.6
go version go1.17.2 darwin/amd64

**Comment by juiceppe** [comment]
Workaround found in:

[Build error on macOS 10.14 (kcItem.SetAccess undefined, undefined: keychain.Access)](https://github.com/99designs/keyring/issues/94)
Add into go.mod: 
`replace github.com/keybase/go-keychain => github.com/99designs/go-keychain v0.0.0-20191008050251-8e49817e8af4
`

**Comment by EAHITechnology** [comment]
go get -u github.com/apache/pulsar-client-go @juiceppe

**Comment by juiceppe** [comment]
> 

I tried that @EAHITechnology  and I couldn't make it work.. I found a different solution that in the end worked as expected :)

**Comment by pgier** [comment]
This should be fixable once https://github.com/99designs/keyring/pull/102 is merged
