### ISSUE TITLE
there was a ticker leak when create producer failed

### ISSUE THREAD

**Issue by NaraLuwan** [apache/pulsar-client-go#729]

**Comment by NaraLuwan** [comment]
The CPU is full when creating a large number of producers fails.

pprof heap 
![image](https://user-images.githubusercontent.com/15198796/154391384-c2119bed-b1dd-45b0-94eb-093d12e751d0.png)

pprof profile
![image](https://user-images.githubusercontent.com/15198796/154391561-73701e4d-8870-4377-b7a3-ab8f94007d90.png)

**Comment by Shoothzj** [comment]
closed by #730
