### ISSUE TITLE
`pulsar-client-go` test cannot pass on apachepulsar/pulsar:latest

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar-client-go#748]
Five days ago, `apachepulsar/pulsar:latest` point on pulsar `2.8.1`, now `apachepulsar/pulsar:latest` point on pulsar `2.9.1`

I verified that test can't pass on neither `2.9.0` or `2.9.1` on https://github.com/apache/pulsar-client-go/pull/746

I also verified that test can paas on pulsar `2.8.2` on https://github.com/apache/pulsar-client-go/pull/747

I suggest we change to `2.8.2` for not blocking the PR, and change back to `apachepulsar/pulsar:latest` when `2.9.2` are released

@wolfstudy @merlimat

**Comment by freeznet** [comment]
context: the failed CI related with https://github.com/apache/pulsar/pull/13885 and https://github.com/apache/pulsar/pull/14176

**Comment by Shoothzj** [comment]
I suggest to merge #747 for unblocking pr.

**Comment by ZiyaoWei** [comment]
I've been trying to run the CI tests using the 2.10.0 rc (lph890127/pulsar:2.10.0) but it's failing in some other way - I'll do some more local testing and meanwhile will file a ticket for creating a nightly build so we can test all the external repos against the latest code in Pulsar.

**Comment by ZiyaoWei** [comment]
It turns out, as @freeznet pointed out in private messages, `TestSendTimeout` would not fail on its own. I did some digging and it seems it would only fail when ran after `TestConsumerSeek` and `TestConsumerMetadata`. Will look into it to see what's going on.

**Comment by ZiyaoWei** [comment]
Actually the tests pass under `lph890127/pulsar:2.10.0-rc4`, so maybe we should temporarily point to `2.8.2` until 2.10 is out?

**Comment by merlimat** [comment]
👍 Makes sense to me
