### ISSUE TITLE
Update license txt files to reflect updated dependency (go-rate)

### ISSUE THREAD

**Issue by shubham1172** [apache/pulsar-client-go#752]
With this PR https://github.com/apache/pulsar-client-go/issues/725. we upgraded https://github.com/beefsack/go-rate to a version that's MIT licensed. This issue suggests updating the same at two places:

(1) distribution/LICENSE.bin.txt
https://github.com/apache/pulsar-client-go/blob/4f50a678d9030828933e03c1a79ae310c38893ad/distribution/LICENSE.bin.txt#L221-L222

(2) distribution/license/LICENSE-go-rate.txt
https://github.com/apache/pulsar-client-go/blob/4f50a678d9030828933e03c1a79ae310c38893ad/distribution/license/LICENSE-go-rate.txt#L1-L7

The new version of go-rate uses MIT instead of GPL-3

**Comment by merlimat** [comment]
Good point. I think we need to have a tool that automatically updates this license file from the dependencies and we should check in the PR that it's consistent.

**Comment by wolfstudy** [comment]
> Good point. I think we need to have a tool that automatically updates this license file from the dependencies and we should check in the PR that it's consistent.

LGTM +1

**Comment by artursouza** [comment]
The license file is still present: https://github.com/apache/pulsar-client-go/blob/master/distribution/license/LICENSE-go-rate.txt
