### ISSUE TITLE
Support keepalive as an optional parameter

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar-client-go#837]
**Is your feature request related to a problem? Please describe.**
When Brokers are autoscaling, brokers will come and go.
We would like to be able to optionally detect a stale broker connection faster.

**Describe the solution you'd like**
Similar to Connection and Operation timeouts (see [link](https://github.com/apache/pulsar-client-go/blob/ea6eccf7ddad548a1ad977a0b72a61b894e6d248/pulsar/client.go#L92-L98)) 
We would like to see an optional parameter to be able to set the Keep Alive value currently a constant here

https://github.com/apache/pulsar-client-go/blob/ea6eccf7ddad548a1ad977a0b72a61b894e6d248/pulsar/internal/connection.go#L117

**Describe alternatives you've considered**
None I am aware of

**Additional context**
CC: @merlimat

**Comment by merlimat** [comment]
@nodece Can you take a look at this one?

**Comment by nodece** [comment]
I'm working on this.

**Comment by nodece** [comment]
I submitted #838 to fix this issue, please help review if you have time, thanks!

**Comment by frankjkelly** [comment]
Thank you @nodece @merlimat

**Comment by frankjkelly** [comment]
Thanks @merlimat - do you have a sense of when we might get a release with this fix?

**Comment by nodece** [comment]
A release should take some time, you can get the latest version by `go get github.com/apache/pulsar-client-go@master`.
