### ISSUE TITLE
Is it possible to create a non persistent topic?

### ISSUE THREAD

**Issue by smthlow** [apache/pulsar-client-go#842]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Shoothzj** [comment]
Hi, @smthlow are you trying to create topic with **pulsar-client-go**. It seems **pulsar-client-go** doesn't offer this ability

**Comment by smthlow** [comment]
> Hi, @smthlow are you trying to create topic with **pulsar-client-go**. It seems **pulsar-client-go** doesn't offer this ability

Thanks for response, do you know any alternative client or an alternative way to be able to do this?

**Comment by Shoothzj** [comment]
@smthlow You might want to see https://github.com/streamnative/pulsarctl
