### ISSUE TITLE
Support backoff parameters as optional parameters

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar-client-go#851]
**Is your feature request related to a problem? Please describe.**

The default backoff parameters are alternatively very aggressive (100ms minimum) and not aggressive enough (60 seconds maximum) for high throughput / short response time environments where we are trying to
* Avoid a "thundering herd" / "retry storm" (increase the minimum backoff)
* But need to fail fast (lower the maximum backoff) 

**Describe the solution you'd like**

Make these settings parameterizable
https://github.com/apache/pulsar-client-go/blob/bd19458b32ff89206c135cc647336e690e99c32f/pulsar/internal/backoff.go#L36-L38

**Describe alternatives you've considered**
None I can think of 

**Additional context**

**Comment by wolfstudy** [comment]
Thanks @frankjkelly feedback, I think this is a very rational requirement, we can implement this function by combining these configuration parameters
