### ISSUE TITLE
ReaderOptions should support BackoffPolicy similar to what was added for ProducerOptions and ConsumerOptions.

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar-client-go#872]
**Is your feature request related to a problem? Please describe.**
Reader implementation needs configurable backoff parameters.

**Describe the solution you'd like**
`ProducerOptions` and `ConsumerOptions` both support `BackOffPolicy` per #853 - we also need that functionality for `ReaderOptions`.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by labuladong** [comment]
Assign to me.
