### ISSUE TITLE
in go mod 1.12 compile error

### ISSUE THREAD

**Issue by sunvooker** [apache/pulsar-client-go#88]
#### Expected behavior
in go program with go mod 1.12

go.mod
`
module assets
go 1.12
require (
	github.com/apache/pulsar-client-go v0.0.0-20191110190923-af5c6d7e1f89
	github.com/go-sql-driver/mysql v1.4.0
	github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
	github.com/spf13/cobra v0.0.5
	golang.org/x/net v0.0.0-20190813141303-74dc4d7220e7 // indirect
	golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456 // indirect
	google.golang.org/grpc v1.24.0
)

`

error output
`
448	go: extracting github.com/pierrec/lz4 v2.0.5+incompatible
449	....
450	....
451	....
452	# github.com/klauspost/compress/zstd
453	....
454	....
455	....
456	/go/pkg/mod/github.com/klauspost/compress@v1.6.2/zstd/enc_fast.go:30:15: undefined: xxhash.Digest
`

**Comment by reugn** [comment]
@sunvooker try `export GO111MODULE=on`

**Comment by jiazhai** [comment]
@sunvooker have you tried the method that @reugn suggested? Does it solve your issue?

**Comment by jiazhai** [comment]
@sunvooker I would like to close this issue. and once needed please re-open it.
