### ISSUE TITLE
Consumer panics on de-serializing message if schema not found on broker

### ISSUE THREAD

**Issue by GPrabhudas** [apache/pulsar-client-go#884]
#### Expected behavior

Should return on error instead of panicking with `panic: runtime error: invalid memory address or nil pointer dereference`

#### Actual behavior
Consumer panics with `panic: runtime error: invalid memory address or nil pointer dereference`

#### Steps to reproduce

How can we reproduce the issue
1. produce message with schema
2. delete schema from broker 
3. consume message

**Comment by nodece** [comment]
Closed by https://github.com/apache/pulsar-client-go/pull/886
