### ISSUE TITLE
support enableBatchIndexAcknowledgment setting

### ISSUE THREAD

**Issue by panszobe** [apache/pulsar-client-go#894]
Problem: *Consume duplicate data after restarting consumer to carry on consuming messages.*

We use AskID() to ack every message  without enableBatchIndexAcknowledgment setting. Usually, we have to set acknowledgmentAtBatchIndexLevelEnabled=true at pulsar server side, and set enableBatchIndexAcknowledgment=true at consumer client side to enable batch index acknowledgment, which could help to solve the problem.

But Community does not support  ***enableBatchIndexAcknowledgment***  this setting,  we need this support.

**Comment by hangc0276** [comment]
@wolfstudy Would you please help take a look? thanks a lot.
