### ISSUE TITLE
Support consumer event listener

### ISSUE THREAD

**Issue by dfarr** [apache/pulsar-client-go#901]
**Describe the solution you'd like**
It would be awesome if the go client supported the consumer event listener, similar to the [java client](https://pulsar.apache.org/api/client/2.10.x/org/apache/pulsar/client/api/ConsumerEventListener.html).

**Is your feature request related to a problem? Please describe.**
We have an application that uses a partitioned topic. On application scale out, we need to know which consumers have been unassigned from a topic/partition in order to clear the internal memory of our application for this partition.

**Describe alternatives you've considered**
We have explored a `Key_Shared` subscription type with a non-partitioned topic. When a scale out of the application occurs with this type of subscription unacked messages are not automatically re-delivered and message consumption is paused until the pending messages are acked/nacked. See apache/pulsar#15705. This behaviour prevents our application from using a `Key_Shared` subscription type.

**Additional context**
- [slack thread](https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1669690833804909)
- [related stackoverflow question](https://stackoverflow.com/questions/74620723/group-messages-by-key-for-pulsar-key-shared-subscription-type)

**Comment by labuladong** [comment]
Assign to me @codelipenghui

**Comment by hugosmitter** [comment]
We're following this issue with great interest. We're interested in proposing this enhancement to be included in the dapr.io pub/sub building block as soon as it's available from the Apache Pulsar community.
