### ISSUE TITLE
[feature request] Support client memory limit

### ISSUE THREAD

**Issue by shibd** [apache/pulsar-client-go#927]
### Motivation

PIP: https://github.com/apache/pulsar/wiki/PIP-74%3A-Pulsar-client-memory-limits

### Alternatives

- Refer to the impl of the producer for the Java client: https://github.com/apache/pulsar/pull/8965
- Refer to the impl of the consumer for the Java client: (Consumer need Support auto scaled consumer receiver queue first)
   - https://github.com/apache/pulsar/pull/14494
   - https://github.com/apache/pulsar/pull/14400

**Comment by shibd** [comment]
> @RobertIndie I'm interested in this feature. Could you assigned it to me? I will take some time to implement it.
Thanks!

Hi, @Gleiphir2769  Great! #955 implemented memory control on the production side. You can look at how to implement the consumer side

**Comment by Gleiphir2769** [comment]
Hi @shibd. All the features have been finished. I think we can close this issue.
