### ISSUE TITLE
[feature request] Support Transaction API 

### ISSUE THREAD

**Issue by liangyepianzhou** [apache/pulsar-client-go#932]
### Motivation
Now, the pulsar-client-go does not support the go-client, so I want to support transaction API for the go client.  
### Solution
Add Transaction API for go client.

**Comment by geniusjoe** [comment]
Since merged in [953](https://github.com/apache/pulsar-client-go/pull/953), can we close this issue as completed? @RobertIndie

**Comment by crossoverJie** [comment]
@geniusjoe Done.
