### ISSUE TITLE
[feature request] Consumer support commulative acknowledge

### ISSUE THREAD

**Issue by shibd** [apache/pulsar-client-go#933]
### Motivation

https://pulsar.apache.org/docs/next/concepts-messaging/#acknowledgment

**Comment by liangyuanpeng** [comment]
Existed issue and PR :
- https://github.com/apache/pulsar-client-go/issues/183
- https://github.com/apache/pulsar-client-go/pull/903

**Comment by shibd** [comment]
Thanks, I will close it.
