### ISSUE TITLE
[feature request] Expose the chunk config of consumer to the reader

### ISSUE THREAD

**Issue by shibd** [apache/pulsar-client-go#935]
## Motivation

About the chunk config of the `Consumer`, we need to make it exposed in `Reader`.

https://github.com/apache/pulsar-client-go/blob/23777362f3d132f98eff56c4f511f761227d8cf4/pulsar/consumer_partition.go#L112-L114

**Comment by CrazyCollin** [comment]
I want to work on this issue, can I have a try?
