### ISSUE TITLE
goroutine leak

### ISSUE THREAD

**Issue by dino-ma** [apache/pulsar-client-go#940]
#### Expected behavior

During the running process of our service, each time we link TCP, the use of FD and coroutine will be increased, and the coroutine will not be released, causing leakage

#### Actual behavior

goroutine leak.

![image](https://user-images.githubusercontent.com/25836943/210559968-dd969695-3599-4261-acf1-df93d4e8bb1a.png)

This part of the log will repeat. I suspect that it is not the same port number that causes new connections to be obtained each time. And the log of the number of connections can be aligned with the number of coroutines.

``
remote_addr="pulsar://x.com:8650"
time="2023-01-04T20:00:22+08:00" level=info msg="Connection is ready" local_addr="x.x.x.x.x:57991" remote_addr="pulsar://x.com:8650"

time="2023-01-04T20:00:22+08:00" level=info msg="Connection is ready" local_addr="x.x.x.x.x:57990" remote_addr="pulsar://x.com:8650"

``
![pprof002](https://user-images.githubusercontent.com/25836943/210563375-cd57056f-9589-4ec0-8ddb-9f515f08e571.svg)

![image](https://user-images.githubusercontent.com/25836943/210563538-ffa9d41b-27d8-4712-93ba-1821f77a43bf.png)
![image](https://user-images.githubusercontent.com/25836943/210563592-311f6bff-8e18-4df5-8c47-d76655178b5a.png)
![image](https://user-images.githubusercontent.com/25836943/210563662-23498bbe-35c0-4778-97f4-522735774042.png)

<img width="898" alt="image" src="https://user-images.githubusercontent.com/25836943/210722814-b13ef69e-745b-4068-9b97-c6eb8385fa01.png">

The connection will be released automatically in the early morning
![image](https://user-images.githubusercontent.com/25836943/210723189-fd2fbcac-a2f0-4b3a-941e-3f150e6c5ef3.png)

It seems that every time the RPC request comes back, the link is not released
<img width="773" alt="image" src="https://user-images.githubusercontent.com/25836943/210723800-8e2c0612-271e-4a03-b9a7-2eea84ff5916.png">

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: 0.9.0

**Comment by dino-ma** [comment]
初步的分析结论是。

连接器并没有复用池子，在每次进行链接行为的时候（look up）会触发此问题。

**Comment by clearcodecn** [comment]
有解决吗 @dino-ma
