### ISSUE TITLE
When a new release?

### ISSUE THREAD

**Issue by fracasula** [apache/pulsar-client-go#995]
Hey guys, when are you planning a new release? I see that v0.9.0 is from October 2022, quite a while ago considering all fixes that got through since then: https://github.com/apache/pulsar-client-go/compare/v0.9.0...master

**Comment by RobertIndie** [comment]
Hi, @fracasula 
The release of go client 0.10.0 will be started soon. For more information, please see: https://lists.apache.org/thread/13owg7m9fgq4z0w3z28mc97gm73jnbwd

**Comment by RobertIndie** [comment]
0.10.0 has been released: https://github.com/apache/pulsar-client-go/releases/tag/v0.10.0

**Comment by fracasula** [comment]
Thanks @RobertIndie :+1:
